import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import * as d from '../src/domain.js';
import {parseBackup,exportBackup,partitionBackups,validateSession} from '../src/backup.js';
const bank=JSON.parse(await fs.readFile(new URL('../data/seed-bank.json',import.meta.url),'utf8'));
const config={type:'written',subjectId:'all',mode:'untimed',kind:'practice',count:10,minutes:30,optionCount:5,pool:'all',family:'all',feedbackAfter:'confirm'};
const make=(overrides={},seed=3)=>d.startSession(d.prepareSession(bank,{...config,...overrides},[],seed,`test-${seed}`),100000);
const answer=(s,item=s.items[0])=>item.type==='written'?item.correctOptionId:Object.fromEntries(item.parts.map(p=>[p.partId,p.kind==='text'?p.accepted[0]:p.kind==='single'?p.correct[0]:p.correct]));
test('the complete seed bank is valid with all five subjects and both practical families',()=>{d.validateBank(bank);assert.equal(bank.questions.length,14);assert.ok(bank.questions.every(q=>q.testOnly));assert.deepEqual(d.SUBJECTS.map(s=>bank.questions.filter(q=>q.subjectId===s.id).length),[2,2,2,2,2]);assert.equal(new Set(bank.questions.filter(q=>q.type==='practical').map(q=>q.family)).size,2);});
test('1000 independent random sessions retain one correct option, no duplicate goal or visible option',()=>{for(let seed=0;seed<1000;seed++){const s=make({optionCount:seed%2?4:5},seed);assert.equal(new Set(s.items.map(i=>i.templateId)).size,10);for(const q of s.items){assert.equal(q.options.length,s.config.optionCount);assert.equal(q.options.filter(o=>o.role==='correct').length,1);assert.equal(new Set(q.options.map(o=>o.content)).size,q.options.length);}}});
test('shared membership is derived and roles depend on question context',()=>{const memberships=d.optionMembership(bank);const shared=Object.entries(memberships).find(([,qs])=>qs.length>1);assert.ok(shared);const links=bank.questions.flatMap(q=>(q.links||[]).filter(l=>l.optionId===shared[0]));assert.ok(links.every(l=>l.contextExplanation));assert.equal(new Set(links.map(l=>l.role)).size,2);});
test('malformed sources, duplicate IDs, unsupported schema and insufficient distractors rejected',()=>{for(const mutate of[b=>b.schemaVersion=99,b=>b.sources[0].url='javascript:alert(1)',b=>b.questions[1].questionId=b.questions[0].questionId,b=>b.questions[0].links=b.questions[0].links.filter(l=>l.role==='correct')]){const b=d.copy(bank);mutate(b);assert.throws(()=>d.validateBank(b));}});
test('rendered snapshots survive later bank changes and repeated regeneration is unnecessary',()=>{const s=make(),before=JSON.stringify(s.items);bank.options[0].content+=' temporary';assert.equal(JSON.stringify(s.items),before);bank.options[0].content=bank.options[0].content.replace(' temporary','');assert.deepEqual(JSON.parse(JSON.stringify(s)).items,s.items);});
test('prepared data has no running timer; start fixes deadline exactly once',()=>{const p=d.prepareSession(bank,{...config,mode:'timed'},[],1,'start');assert.equal(p.startedAt,null);const s=d.startSession(p,2000);assert.equal(s.expiresAt,1802000);assert.throws(()=>d.startSession(s,100));});
test('timed early completion, exact expiry, late answers and repeated submit',()=>{let s=make({mode:'timed',minutes:1});const item=s.items[0];s=d.setAnswer(s,item.instanceId,answer(s),100100);s=d.setAnswer(s,s.items[1].instanceId,answer(s,s.items[1]),160000);assert.equal(s.status,'expired');assert.equal(s.result.correct,1);assert.equal(s.result.unanswered,9);assert.equal(s.endedAt,160000);assert.equal(s.elapsedMs,60000);assert.deepEqual(d.finalize(s,'submitted',170000),s);});
test('untimed confirmations are idempotent and completed set preserves unanswered denominator',()=>{let s=make();const item=s.items[0];assert.throws(()=>d.confirmAnswer(s,item.instanceId));s=d.setAnswer(s,item.instanceId,answer(s),100001);s=d.confirmAnswer(s,item.instanceId,100002);s=d.confirmAnswer(s,item.instanceId,100003);assert.equal(s.attempts.length,1);s=d.finalize(s,'submitted',200000);assert.equal(s.result.total,10);assert.equal(s.result.unanswered,9);assert.equal(s.result.score,.1);assert.equal(s.elapsedMs,undefined);});
test('finalized choice cannot be edited; navigating does not create attempts',()=>{let s=make();const item=s.items[0];s=d.setAnswer(s,item.instanceId,answer(s),100001);assert.equal(s.attempts.length,0);s=d.confirmAnswer(s,item.instanceId,100002);assert.throws(()=>d.setAnswer(s,item.instanceId,item.options[0].optionId,100003));});
test('all practical accepted answers grade deterministically; ungraded narrative stays separate',()=>{const s=make({type:'practical',subjectId:'practical',count:4});for(const item of s.items){const a=answer(s,item);assert.equal(d.grade(item,a).status,'correct');assert.equal(d.grade(item,{freeResponse:'서술만 입력'}).status,'unanswered');for(const p of item.parts)if(p.kind==='multi'){assert.equal(d.grade(item,{[p.partId]:[...p.correct,...p.correct]}).parts.find(x=>x.partId===p.partId).correct,false);}}});
test('exported help is separated from first-attempt learning outcomes',()=>{let s=make();const item=s.items[0];s.exported[item.instanceId]=true;s.exposureEvents=[{key:`${item.templateId}@${item.learningGoalRevision}`,kind:'prompt',at:100001}];s=d.setAnswer(s,item.instanceId,answer(s),100002);s=d.confirmAnswer(s,item.instanceId,100003);const stats=d.statistics([s],{testOnly:true});assert.equal(stats.assisted,1);assert.equal(stats.first.count,0);});
test('test seeds excluded by default, but explicitly selected test records visible',()=>{let s=make();s=d.setAnswer(s,s.items[0].instanceId,answer(s),100001);s=d.confirmAnswer(s,s.items[0].instanceId,100002);assert.equal(d.statistics([s]).first.count,0);assert.equal(d.statistics([s],{testOnly:true}).first.count,1);});
test('abandoned timed answers do not become attempts; conversion carries drafts only',()=>{let s=make({mode:'timed'});s=d.setAnswer(s,s.items[0].instanceId,answer(s),100001);assert.equal(d.finalize(s,'abandoned',100002).attempts.length,0);const {old,next}=d.convertToUntimed(s,'converted',100003);assert.equal(old.status,'converted');assert.equal(old.result,null);assert.deepEqual(next.answers,s.answers);assert.equal(next.attempts.length,0);assert.equal(next.config.mode,'untimed');assert.equal(next.expiresAt,null);});
test('extension preserves first start and marks modified configuration',()=>{const s=make({mode:'timed',minutes:1}),n=d.extendTime(s,2,110000);assert.equal(n.startedAt,s.startedAt);assert.equal(n.expiresAt,s.expiresAt+120000);assert.equal(n.timingChanges.length,1);assert.throws(()=>d.extendTime(s,1440,110000));});
test('monotonic active clock and recovery deadline survive clock changes',()=>{const s=make({mode:'timed',minutes:1});const t=d.timeState(s,900000,{wall:100000,mono:0,monoNow:10000});assert.equal(t.now,110000);assert.equal(t.expired,false);assert.equal(t.trusted,false);assert.equal(d.timeState(s,170000).expired,true);s.lastWallAt=140000;assert.equal(d.timeState(s,100000).trusted,false);});
test('independent prompt excludes reference, rubric and correct key; comparison includes them',()=>{const s=make({type:'practical',subjectId:'practical',count:4}),item=s.items[0];const p=d.createPrompt(s,item,{includeReference:false});assert.ok(!p.includes(item.referenceAnswer));assert.ok(!p.includes('참고 답안 시작'));assert.ok(!p.includes('평가 기준 시작'));assert.ok(p.includes(item.materials[0].content));const reference=d.createPrompt(s,item);assert.ok(reference.includes(item.referenceAnswer));assert.ok(reference.includes('미작성'));s.config.mode='timed';assert.throws(()=>d.createPrompt(s,item));});
test('backup import round trip preserves snapshots, Unicode and exact strings',()=>{const s=make({type:'practical',subjectId:'practical',count:4});s.answers[s.items[0].instanceId]={freeResponse:'<script>alert("안녕")</script>\nA & B\n'};const b=parseBackup(exportBackup([s]));assert.deepEqual(b.sessions,[s]);assert.equal(validateSession(s),s);});
test('backup refuses forged scores, bad version, duplicate sessions and unsafe keys',()=>{const s=make();let raw=JSON.parse(exportBackup([s]));raw.sessions.push(s);assert.throws(()=>parseBackup(JSON.stringify(raw)));raw=JSON.parse(exportBackup([s]));raw.schemaVersion=99;assert.throws(()=>parseBackup(JSON.stringify(raw)));assert.throws(()=>parseBackup('{"__proto__":{"polluted":true}}'));});
test('new and wrong selectors do not silently fabricate or duplicate labels',()=>{assert.throws(()=>d.prepareSession(bank,{...config,count:100},[],1,'too-many'));assert.throws(()=>d.prepareSession(bank,{...config,kind:'mock',count:100},[],1,'mock'));let s=make();s=d.setAnswer(s,s.items[0].instanceId,s.items[0].options.find(o=>o.role==='distractor').optionId,100001);s=d.confirmAnswer(s,s.items[0].instanceId,100002);assert.equal(d.eligibleQuestions(bank,{...config,pool:'wrong'},[s]).length,1);assert.equal(d.eligibleQuestions(bank,{...config,pool:'new'},[s]).length,9);});
test('invalid correction preserves original result but excludes adjusted denominator',async()=>{let s=make({mode:'timed'});s=d.finalize(s,'submitted',101000);const original=JSON.stringify(s);const c={questionId:s.items[0].questionId,revision:1,kind:'invalid',reason:'검토 중',effectiveAt:'2026-10-01T00:00:00Z'};const adjusted=await d.adjustedResult(s,[c]);assert.equal(adjusted.excluded,1);assert.equal(adjusted.result.total,9);assert.equal(JSON.stringify(s),original);assert.equal(d.statistics([s],{mode:'timed',testOnly:true,corrections:[c]}).invalidExcluded,1);});
test('explicit key correction needs the exact displayed snapshot hash',async()=>{let s=make({mode:'timed'});const item=s.items[0],wrong=item.options.find(o=>o.role==='distractor').optionId;s=d.setAnswer(s,item.instanceId,wrong,100001);s=d.finalize(s,'submitted',100002);const c={questionId:item.questionId,revision:1,kind:'key',reason:'명백한 키 정정 테스트',correctOptionId:wrong,snapshotHash:await d.snapshotHash(item)};assert.equal((await d.adjustedResult(s,[c])).result.correct,1);assert.equal((await d.adjustedResult(s,[{...c,snapshotHash:'different'}])).result.correct,0);assert.equal(s.result.correct,0);});
test('freeze closes exactly at Korea midnight; persistent finalization wins even before deadline',()=>{assert.equal(d.releaseAllowed({now:d.FREEZE_AT-1}),true);assert.equal(d.releaseAllowed({now:d.FREEZE_AT}),false);assert.equal(d.releaseAllowed({now:d.FREEZE_AT-1000,finalized:true}),false);});

test('large backup splits by whole sessions with bounded importable files and exact roundtrip',()=>{const sessions=Array.from({length:7},(_,i)=>make({type:'practical',subjectId:'practical',count:4},i+5000));const single=partitionBackups([sessions[0]])[0].byteLength;const limit=single*2+100;const files=partitionBackups(sessions,{maxBytes:limit});assert.ok(files.length>1);const restored=files.flatMap(file=>{assert.equal(file.restorable,true);assert.ok(file.byteLength<=limit);assert.equal(file.byteLength,new TextEncoder().encode(file.content).byteLength);return parseBackup(file.content).sessions;});assert.deepEqual(restored,sessions);assert.equal(new Set(restored.map(s=>s.sessionId)).size,7);});
test('backup partitions at exact byte and session-count boundaries without truncation',()=>{const sessions=[make({},6001),make({},6002),make({},6003)];const one=partitionBackups([sessions[0]])[0];assert.equal(partitionBackups([sessions[0]],{maxBytes:one.byteLength})[0].restorable,true);assert.equal(partitionBackups([sessions[0]],{maxBytes:one.byteLength-1})[0].restorable,false);assert.deepEqual(partitionBackups(sessions,{maxSessions:1}).map(p=>p.sessionCount),[1,1,1]);assert.deepEqual(parseBackup(partitionBackups([])[0].content).sessions,[]);});
test('oversized single session is explicitly preservation-only and kept byte-complete',()=>{const s=make({type:'practical',subjectId:'practical',count:4},7000);s.answers[s.items[0].instanceId]={freeResponse:'가'.repeat(100000)};const parts=partitionBackups([s],{maxBytes:50000});assert.equal(parts.length,1);assert.equal(parts[0].restorable,false);assert.match(parts[0].filename,/가져오기불가/);assert.match(parts[0].reason,/재가져오기 할 수 없습니다/);assert.deepEqual(JSON.parse(parts[0].content).sessions,[s]);});

test('effective invalid correction prevents new presentation even if old published status remains',()=>{const b=d.copy(bank),q=b.questions[0];b.corrections=[{questionId:q.questionId,revision:q.revision,kind:'invalid',reason:'다중 정답 발견',effectiveAt:'2026-01-01T00:00:00Z'}];assert.equal(d.eligibleQuestions(b,config).some(item=>item.questionId===q.questionId),false);b.corrections[0].revision++;assert.equal(d.eligibleQuestions(b,config).some(item=>item.questionId===q.questionId),true);b.corrections[0].revision=q.revision;b.corrections[0].effectiveAt='2099-01-01T00:00:00Z';assert.equal(d.eligibleQuestions(b,config).some(item=>item.questionId===q.questionId),true);});

test('invalid correction also removes untimed confirmed and unconfirmed items from adjusted set denominator',async()=>{let s=make();const q=s.items[0];s=d.setAnswer(s,q.instanceId,q.correctOptionId,100001);s=d.confirmAnswer(s,q.instanceId,100002);s=d.finalize(s,'submitted',100003);const original=JSON.stringify(s);for(const item of [q,s.items[1]]){const r=await d.adjustedResult(s,[{questionId:item.questionId,revision:item.revision,kind:'invalid',reason:'무효',effectiveAt:'2026-01-01T00:00:00Z'}]);assert.equal(r.excluded,1);assert.equal(r.result.total,9);assert.equal(r.result.maxPoints,9);}assert.equal(JSON.stringify(s),original);});
test('native hidden attribute always overrides component display rules',async()=>{const css=await fs.readFile(new URL('../style.css',import.meta.url),'utf8');assert.match(css,/\[hidden\]\s*\{\s*display\s*:\s*none\s*!important\s*;?\s*\}/);});

test('AI prompt separates narrative rubric from fixed keys without double counting and preserves narrative instruction',()=>{const s=make({type:'practical',subjectId:'practical',count:4}),q=s.items[0];const p=d.createPrompt(s,q);assert.ok(p.includes(q.freeResponsePrompt));assert.match(p,/서술형 평가 기준 시작: 합계 10점/);assert.match(p,/고정 답안 참고 키 시작: 앱 자동 채점용 별도 기준/);assert.ok(p.includes('두 배점을 더하지 마세요'));assert.ok(p.includes('자유 서술 답안이 없으면 미작성'));const independent=d.createPrompt(s,q,{includeReference:false});assert.ok(independent.includes(q.freeResponsePrompt));assert.ok(!independent.includes(q.referenceAnswer));assert.ok(!independent.includes('고정 답안 참고 키 시작'));assert.ok(!independent.includes('서술형 평가 기준 시작'));});
