import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateEditorialLedgers,validateReleaseLedger,regularCoverage,editorialHash,editorialContentHash,editorialBlindPackage,editorialChangedPaths,editorialComponentStates,editorialContent,validateJsonSchema} from '../scripts/validate-round.mjs';
import {presentQuestion,rng,grade,prepareSession,startSession,setAnswer,confirmAnswer,snapshotHash} from '../src/domain.js';
import {exportBackup,parseBackup} from '../src/backup.js';
import {practiceConfig} from '../src/workflows.js';
const raw=fs.readFileSync(new URL('../data/releases/2026.10.02-regular.1/bank.json',import.meta.url),'utf8'), baseline=JSON.parse(raw);
const prior=JSON.parse(fs.readFileSync(new URL('../docs/rounds/round-001.json',import.meta.url),'utf8'));
const schema=JSON.parse(fs.readFileSync(new URL('../docs/corrections/editorial-ledger.schema.json',import.meta.url),'utf8'));
const clone=v=>structuredClone(v);
const change=(id,before,after)=>({id,beforeRevision:before.revision??1,afterRevision:after.revision??1,beforeSha256:editorialHash(before),afterSha256:editorialHash(after)});
function fixture(type='written') {
 const bank=clone(baseline),q=bank.questions.find(q=>!q.testOnly&&q.type===type),before=baseline.questions.find(old=>old.questionId===q.questionId),p=prior.candidates.find(c=>c.questionId===q.questionId);
 bank.bankVersion='fixture-editorial.1';bank.releasedAt='2026-10-02T08:04:00Z';bank.changeSummary='Synthetic editorial test fixture, never a public release.';bank.editorialRoundId='editorial-fixture';q.revision++;
 const optionChanges=[],practicalChoiceChanges=[];
 if(type==='written') {q.links.forEach(l=>l.contextExplanation='');const o=bank.options.find(o=>o.optionId===q.links[1].optionId),old=clone(o);o.content+=' (검사 예시)';o.revision++;q.links[1].optionRevision++;optionChanges.push(change(o.optionId,old,o));}
 else {const o=q.parts[0].choices[1],old=clone(o);o.text+=' (검사 예시)';o.revision=2;practicalChoiceChanges.push(change(o.id,old,o));}
 const gates=Object.fromEntries(['blindSolve','sourceCheck','ambiguityCheck','authoringAccessibility','structuralCheck'].map(name=>[name,{result:'pass',reviewerId:'fresh-editorial-reviewer',summary:'Synthetic independent review fixture.',evidenceRefs:name==='sourceCheck'?[q.sourceRefs[0]]:[]}]));
 const c={targetPaths:editorialChangedPaths(baseline,bank,q.questionId),correctionId:'editorial-fixture-item',issueId:'distractor-quality',questionId:q.questionId,templateId:q.templateId,learningGoalId:p.learningGoalId,learningGoalRevision:q.learningGoalRevision,type:q.type,subjectId:q.subjectId,priorAcceptedRef:{roundId:prior.roundId,candidateId:p.candidateId,ledgerPath:'docs/rounds/round-001.json',bankVersion:baseline.bankVersion,bankSha256:editorialHash(raw),questionRevision:before.revision,contentSha256:editorialContentHash(baseline,before)},defect:'Synthetic wording defect used only to test strict editorial authorization.',revision:q.revision,authorId:'editorial-author',evidence:clone(p.evidence),optionChanges,practicalChoiceChanges,attemptCount:1,cycles:[{cycle:1,revision:q.revision,startedAt:'2026-10-02T08:01:00Z',finishedAt:'2026-10-02T08:02:00Z',gates,outcome:'accepted',summary:'Synthetic complete review fixture.',contentSha256:editorialContentHash(bank,q),blindPackageSha256:editorialHash(editorialBlindPackage(bank,q))}],decision:'accepted',reasonCodes:['accepted_all_gates'],decisionSummary:'Synthetic accepted editorial fixture.',publishedBankVersion:null};
 const e={ledgerSchemaVersion:1,kind:'accepted_content_editorial',campaignId:'2026-exam-final',correctionRoundId:'editorial-fixture',prdVersion:'1.9',timezone:'Asia/Seoul',status:'closed',startedAt:'2026-10-02T08:00:00Z',decisionDeadline:'2026-10-02T10:00:00Z',closedAt:'2026-10-02T08:03:00Z',policy:{maxCycles:3,maxRoundHours:4,newKnowledgeItems:0},baseline:{sourceCommit:'a'.repeat(40),bankVersion:baseline.bankVersion,bankSha256:editorialHash(raw),regularWrittenBySubject:regularCoverage(baseline).regularWrittenBySubject,regularPractical:8},changedQuestionIds:[q.questionId],changedOptionIds:optionChanges.map(v=>v.id),changedPracticalChoiceIds:practicalChoiceChanges.map(v=>v.id),corrections:[c],counts:{registered:1,accepted:1,rejected:0,pending:0,newRegular:0,revisedRegular:1,publishedRevisedRegular:0},coverageAfter:regularCoverage(baseline),publication:{status:'not_attempted',commit:null,bankVersion:bank.bankVersion,bankSha256:null,verifiedAt:null,url:null,blockers:[]},validation:[],nextAction:'Continue actual coverage expansion without counting editorial revisions as new knowledge.',summary:'Synthetic editorial fixture.'};
 const f={bank,q,before,c,e,banks:new Map([[baseline.bankVersion,{raw}]])};refresh(f);return f;
}
function bindReviewPackage(f,cycle=f.c.cycles.at(-1)) {const path=`docs/corrections/evidence/${f.e.correctionRoundId}-cycle-${cycle.cycle}.json`,raw=JSON.stringify({evidenceSchemaVersion:1,purpose:'immutable_editorial_review_input',correctionRoundId:f.e.correctionRoundId,cycle:cycle.cycle,items:[{correctionId:f.c.correctionId,...editorialContent(f.bank,f.q)}]});f.reviewPackages??=new Map();f.reviewPackages.set(path,{raw});Object.assign(cycle,{reviewPackagePath:path,reviewPackageSha256:editorialHash(raw),componentStates:editorialComponentStates(f.bank,f.q)});}
function refresh(f,{rehash=true}={}) {if(rehash){f.c.targetPaths=editorialChangedPaths(baseline,f.bank,f.q.questionId);f.c.cycles.at(-1).contentSha256=editorialContentHash(f.bank,f.q);f.c.cycles.at(-1).blindPackageSha256=editorialHash(editorialBlindPackage(f.bank,f.q));bindReviewPackage(f);}const bytes=JSON.stringify(f.bank);f.banks.set(f.bank.bankVersion,{raw:bytes});f.e.publication.bankSha256=editorialHash(bytes);f.manifest={schemaVersion:1,bankVersion:f.bank.bankVersion,releasedAt:f.bank.releasedAt,file:`releases/${f.bank.bankVersion}/bank.json`,sha256:editorialHash(bytes),changeSummary:f.bank.changeSummary,finalRelease:false};}
function check(f){return validateReleaseLedger([prior],{manifest:f.manifest,banks:f.banks,reviewPackages:f.reviewPackages,editorials:[f.e]});}
function pass(f){const r=check(f);assert.equal(r.ok,true,r.errors.join('\n'));}
function fail(f,re){const r=check(f);assert.equal(r.ok,false,'invalid editorial release passed');assert.match(r.errors.join('\n'),re);}

test('bounded editorial fixture passes after closed earlier expansion, preserves cumulative coverage',()=>{const f=fixture();assert.deepEqual(validateJsonSchema(f.e,schema),[]);pass(f);assert.deepEqual(regularCoverage(f.bank),regularCoverage(baseline));});
test('default expansion path still rejects all unapproved historical mutations',()=>{const f=fixture();const r=validateReleaseLedger([prior],{manifest:f.manifest,banks:f.banks});assert.equal(r.ok,false);assert.match(r.errors.join('\n'),/explicit publication.bankVersion/);});
test('exactly one expansion OR editorial ledger may authorize a bank',()=>{const f=fixture(),r=clone(prior);r.publication.bankVersion=f.bank.bankVersion;const result=validateReleaseLedger([prior,r],{manifest:f.manifest,banks:f.banks,reviewPackages:f.reviewPackages,editorials:[f.e]});assert.match(result.errors.join('\n'),/exactly one expansion OR editorial/);});
test('historical sources, seeds, keys, point values and question/part identity never relax',()=>{
 for(const mutate of [f=>f.bank.sources[0].title+='x',f=>f.bank.questions.find(q=>q.testOnly).stem+='x',f=>f.q.links[0].role='distractor',f=>f.q.learningGoalRevision++,f=>f.q.templateId+='x',f=>f.bank.questions.pop(),f=>f.bank.corrections.push({questionId:f.q.questionId,revision:1,kind:'invalid',reason:'test',effectiveAt:'2026-10-02T08:00:00Z'})]){const f=fixture();mutate(f);refresh(f);assert.equal(check(f).ok,false);}
 for(const mutate of [f=>f.q.parts[0].points++,f=>f.q.parts.reverse(),f=>f.q.parts[0].correct=[f.q.parts[0].choices[1].id],f=>f.q.rubric[0].points++]){const f=fixture('practical');mutate(f);refresh(f);fail(f,/protected|invalid active bank/);}
});
test('question and option exact-change allowlists cannot hide mutations or invent additions',()=>{for(const mutate of [f=>f.e.changedQuestionIds=[],f=>f.e.changedOptionIds=[],f=>f.c.optionChanges=[],f=>f.c.optionChanges[0].beforeSha256='a'.repeat(64),f=>f.bank.questions.push({...clone(f.q),questionId:'renamed-new',templateId:'renamed-goal'})]){const f=fixture();mutate(f);refresh(f);assert.equal(check(f).ok,false);}});
test('prior accepted references must match original verified record and hash',()=>{for(const mutate of [f=>f.c.priorAcceptedRef.candidateId='not-accepted',f=>f.c.priorAcceptedRef.bankSha256='a'.repeat(64),f=>f.c.priorAcceptedRef.contentSha256='b'.repeat(64),f=>f.c.priorAcceptedRef.questionRevision=2]){const f=fixture();mutate(f);fail(f,/priorAcceptedRef|prior accepted/);}});
test('all five gates are bound to exact final content and neutral blind package',()=>{for(const mutate of [f=>f.c.cycles[0].gates.sourceCheck.result='not_run',f=>f.c.cycles[0].contentSha256='a'.repeat(64),f=>f.c.cycles[0].blindPackageSha256='a'.repeat(64),f=>f.q.stem+='x']){const f=fixture();mutate(f);refresh(f,{rehash:false});assert.equal(check(f).ok,false);}});
test('original author, original gate reviewer and current author cannot solve blinded editorial revision',()=>{for(const reviewer of [prior.candidates[0].authorId,prior.candidates[0].cycles[0].gates.blindSolve.reviewerId,'editorial-author']){const f=fixture();f.c.cycles[0].gates.blindSolve.reviewerId=reviewer;fail(f,/blind reviewer|independent reviewer/);}});
test('same failed issue cannot reset cycles under another ledger or IDs',()=>{const f=fixture(),e=clone(f.e);e.correctionRoundId='editorial-again';e.corrections[0].correctionId='renamed';e.corrections[0].issueId='also-renamed';const r=validateEditorialLedgers([f.e,e],{ledgers:[prior],banks:f.banks});assert.equal(r.ok,false);assert.match(r.errors.join('\n'),/reset a failed/);assert.match(r.errors.join('\n'),/overlaps/);});
test('started cycles, deadline, future timestamps and pending closures cannot be hidden',()=>{for(const mutate of [f=>f.c.attemptCount=0,f=>f.c.attemptCount=4,f=>f.e.decisionDeadline='2026-10-02T12:00:00Z',f=>f.e.closedAt='2026-10-02T10:01:00Z',f=>f.c.cycles[0].finishedAt='2026-10-02T10:01:00Z',f=>f.c.decision='pending']){const f=fixture();mutate(f);assert.equal(check(f).ok,false);}});
test('written link and option revisions must advance together',()=>{const f=fixture();f.bank.options.find(o=>o.optionId===f.e.changedOptionIds[0]).revision=1;refresh(f);fail(f,/revision|invalid active bank/);});
test('practical choice revisions use legacy implicit one and reject stale/forged revision/hash',()=>{pass(fixture('practical'));for(const mutate of [f=>delete f.q.parts[0].choices[1].revision,f=>f.q.parts[0].choices[1].revision=3,f=>f.c.practicalChoiceChanges[0].beforeRevision=2,f=>f.c.practicalChoiceChanges[0].afterSha256='0'.repeat(64),f=>f.e.changedPracticalChoiceIds=[]]){const f=fixture('practical');mutate(f);refresh(f);fail(f,/choice|revision/);}});
test('new counts and hosted publication remain separate from accepted revisions',()=>{const f=fixture();f.e.counts.newRegular=1;fail(f,/constant 0|counts/);const g=fixture();g.e.counts.publishedRevisedRegular=1;fail(g,/counts/);const h=fixture();h.c.publishedBankVersion=h.bank.bankVersion;fail(h,/verified release|counts/);});
test('all revised written questions get strict authoring even if a different option was edited',()=>{const f=fixture(),l=f.q.links[0],o=f.bank.options.find(o=>o.optionId===l.optionId);l.contextExplanation=o.explanation;refresh(f);fail(f,/explanation authoring|공통 해설/);});
test('neutral blind packages expose no keys, source metadata, explanations or semantic identifiers',()=>{for(const type of ['written','practical']){const f=fixture(type),p=editorialBlindPackage(f.bank,f.q);const text=JSON.stringify(p);for(const forbidden of ['questionId','optionId','correct','explanation','sourceRefs','reviewNote','referenceAnswer','rubric','templateId','revision'])assert(!text.includes('"'+forbidden+'"'));assert(!text.includes(f.q.questionId));assert.equal(p.stem,f.q.stem);}});
test('source appends need reviewed evidence and cannot remove original references',()=>{const f=fixture(),s={...clone(f.bank.sources[0]),id:'new-primary',url:'https://example.org/new-primary'};f.bank.sources.push(s);f.q.sourceRefs.push(s.id);refresh(f);fail(f,/matching reviewed primary/);f.c.evidence.push({sourceId:s.id,title:s.title,url:s.url,version:s.version,location:s.location,checkedAt:'2026-10-02T08:00:00Z',summary:'Synthetic evidence.',rights:s.rights});pass(f);f.q.sourceRefs.shift();refresh(f);fail(f,/never remove/);});
test('same stable learning-goal identity, snapshot hash and backups survive editorial bank arrival',async()=>{const f=fixture('practical'),before=presentQuestion(baseline,f.before,5,rng(3)),after=presentQuestion(f.bank,f.q,5,rng(3));assert.equal(before.templateId,after.templateId);assert.equal(before.learningGoalRevision,after.learningGoalRevision);const key=item=>Object.fromEntries(item.parts.map(p=>[p.partId,p.kind==='text'?p.accepted[0]:p.kind==='single'?p.correct[0]:p.correct]));assert.deepEqual(grade(before,key(before)),grade(after,key(after)));let session=startSession(prepareSession(baseline,practiceConfig('practical',{count:1}),[],4,'editorial-backup'),1);const snapshot=JSON.stringify(session.items),hashes=await Promise.all(session.items.map(snapshotHash));const item=session.items[0];session=setAnswer(session,item.instanceId,key(item),2);session=confirmAnswer(session,item.instanceId,3);const saved=exportBackup([session]),restored=parseBackup(saved).sessions[0];assert.deepEqual(restored,session);assert.equal(JSON.stringify(restored.items),snapshot);assert.deepEqual(await Promise.all(restored.items.map(snapshotHash)),hashes);});

function verifyFixture(f) {f.e.publication.status='verified';f.e.publication.commit='b'.repeat(40);f.e.publication.verifiedAt='2026-10-02T08:05:00Z';f.e.publication.url='https://example.org/editorial-fixture/';f.c.publishedBankVersion=f.bank.bankVersion;f.e.counts.publishedRevisedRegular=1;return f;}
function successorFixture() {
 const first=verifyFixture(fixture('practical')),e=clone(first.e),bank=clone(first.bank),q=bank.questions.find(q=>q.questionId===first.q.questionId),c=e.corrections[0];
 bank.bankVersion='fixture-editorial.2';bank.editorialRoundId='editorial-successor';bank.releasedAt='2026-10-02T08:10:00Z';q.revision++;
 const oldChoice=clone(q.parts[0].choices[1]);q.parts[0].choices[1].text+=' 다음 검토';q.parts[0].choices[1].revision++;
 e.correctionRoundId=bank.editorialRoundId;e.startedAt='2026-10-02T08:06:00Z';e.closedAt='2026-10-02T08:09:00Z';e.baseline.bankVersion=first.bank.bankVersion;e.baseline.bankSha256=first.e.publication.bankSha256;
 e.publication={status:'not_attempted',commit:null,bankVersion:bank.bankVersion,bankSha256:null,verifiedAt:null,url:null,blockers:[]};e.counts.publishedRevisedRegular=0;
 c.correctionId='successor-new-defect';c.issueId='genuinely-later-defect';c.revision=q.revision;c.authorId='successor-author';c.publishedBankVersion=null;c.priorAcceptedRef={roundId:first.e.correctionRoundId,candidateId:first.c.correctionId,ledgerPath:`docs/corrections/${first.e.correctionRoundId}.json`,bankVersion:first.bank.bankVersion,bankSha256:first.e.publication.bankSha256,questionRevision:first.q.revision,contentSha256:editorialContentHash(first.bank,first.q)};
 c.practicalChoiceChanges=[change(oldChoice.id,oldChoice,q.parts[0].choices[1])];c.targetPaths=editorialChangedPaths(first.bank,bank,q.questionId);
 c.cycles[0].revision=q.revision;c.cycles[0].startedAt='2026-10-02T08:07:00Z';c.cycles[0].finishedAt='2026-10-02T08:08:00Z';for(const g of Object.values(c.cycles[0].gates))g.reviewerId='successor-fresh-reviewer';c.cycles[0].contentSha256=editorialContentHash(bank,q);c.cycles[0].blindPackageSha256=editorialHash(editorialBlindPackage(bank,q));
 const bytes=JSON.stringify(bank),banks=new Map(first.banks);banks.set(bank.bankVersion,{raw:bytes});e.publication.bankSha256=editorialHash(bytes);
 const manifest={...first.manifest,bankVersion:bank.bankVersion,file:`releases/${bank.bankVersion}/bank.json`,releasedAt:bank.releasedAt,sha256:editorialHash(bytes)};
 const f={first,e,bank,q,c,banks,manifest,reviewPackages:new Map(first.reviewPackages)};bindReviewPackage(f);return f;
}
function checkSuccessor(f) {return validateReleaseLedger([prior],{manifest:f.manifest,banks:f.banks,reviewPackages:f.reviewPackages,editorials:[f.first.e,f.e],now:Date.parse('2026-10-02T08:12:00Z')});}
test('later genuine editorial episode may advance a verified accepted predecessor while prior history remains valid',()=>{const f=successorFixture(),r=checkSuccessor(f);assert.equal(r.ok,true,r.errors.join('\n'));});
test('draft predecessor and stale baseline cannot authorize a later editorial successor',()=>{const f=successorFixture();f.first.e.publication.status='committed_unverified';f.first.e.publication.verifiedAt=null;f.first.c.publishedBankVersion=null;f.first.e.counts.publishedRevisedRegular=0;assert.equal(checkSuccessor(f).ok,false);const g=successorFixture();g.e.baseline.bankVersion=baseline.bankVersion;g.e.baseline.bankSha256=editorialHash(raw);assert.equal(checkSuccessor(g).ok,false);});
test('later fresh solver cannot reuse any ancestor author or key-visible reviewer',()=>{for(const reviewer of ['fresh-editorial-reviewer','editorial-author',prior.candidates.find(c=>c.type==='practical').authorId]){const f=successorFixture();f.c.cycles[0].gates.blindSolve.reviewerId=reviewer;const r=checkSuccessor(f);assert.equal(r.ok,false);assert.match(r.errors.join('\n'),/previously key-visible/);}});
test('verified bank must count every revised question and verification follows release and persistent freeze',()=>{for(const mutate of [f=>{f.c.publishedBankVersion=null;f.e.counts.publishedRevisedRegular=0;},f=>f.e.publication.verifiedAt='2026-10-02T08:03:30Z']){const f=verifyFixture(fixture());mutate(f);assert.equal(check(f).ok,false);}const f=verifyFixture(fixture());const r=validateReleaseLedger([prior],{manifest:f.manifest,banks:f.banks,reviewPackages:f.reviewPackages,editorials:[f.e],publicationState:{finalized:true,finalizedAt:'2026-10-02T08:04:00Z'}});assert.equal(r.ok,false);assert.match(r.errors.join('\n'),/after persistent freeze/);});
test('bookkeeping-only revisions cannot manufacture revised counts',()=>{const f=fixture('practical'),q=f.q;Object.assign(q,clone(f.before),{revision:2});f.c.practicalChoiceChanges=[];f.e.changedPracticalChoiceIds=[];refresh(f);fail(f,/minimum items|substantive authored changes/);});
test('supplied current-time release gate rejects future release timestamp',()=>{const f=fixture();const r=validateReleaseLedger([prior],{manifest:f.manifest,banks:f.banks,reviewPackages:f.reviewPackages,editorials:[f.e],now:Date.parse('2026-10-02T08:03:00Z')});assert.equal(r.ok,false);assert.match(r.errors.join('\n'),/new version inside campaign/);});
test('docs-only validation keeps current verified publication valid, but rejects manifest rollback to an older verified bank',()=>{const f=verifyFixture(fixture());const valid=validateReleaseLedger([prior],{manifest:f.manifest,banks:f.banks,reviewPackages:f.reviewPackages,editorials:[f.e],now:Date.parse('2026-10-02T08:06:00Z')});assert.equal(valid.ok,true,valid.errors.join('\n'));const oldManifest=JSON.parse(fs.readFileSync(new URL('../data/manifest.json',import.meta.url)));const old={...oldManifest,bankVersion:baseline.bankVersion,file:`releases/${baseline.bankVersion}/bank.json`,releasedAt:baseline.releasedAt,sha256:editorialHash(raw),changeSummary:baseline.changeSummary};const result=validateReleaseLedger([prior],{manifest:old,banks:f.banks,reviewPackages:f.reviewPackages,editorials:[f.e],now:Date.parse('2026-10-02T08:06:00Z')});assert.equal(result.ok,false);assert.match(result.errors.join('\n'),/older than the latest verified/);});

function twoCycleFixture(type='written') {
 const f=fixture(type),first=f.c.cycles[0];first.outcome='revise';first.gates.authoringAccessibility.result='fail';
 f.q.revision=3;f.c.revision=3;f.c.attemptCount=2;
 if(type==='written'){const o=f.bank.options.find(o=>o.optionId===f.q.links[1].optionId),old=baseline.options.find(x=>x.optionId===o.optionId);o.content+=' 재검토';o.revision++;f.q.links[1].optionRevision++;f.c.optionChanges=[change(o.optionId,old,o)];}
 else {const o=f.q.parts[0].choices[1],old=f.before.parts[0].choices[1];o.text+=' 재검토';o.revision++;f.c.practicalChoiceChanges=[change(o.id,old,o)];}
 const next=clone(first);Object.assign(next,{cycle:2,revision:3,startedAt:'2026-10-02T08:02:10Z',finishedAt:'2026-10-02T08:02:50Z',outcome:'accepted'});for(const g of Object.values(next.gates)){g.result='pass';g.reviewerId='fresh-second-cycle-reviewer';}f.c.cycles.push(next);refresh(f);return f;
}
test('immutable review input bytes bind every cycle and component state to exact reviewed content',()=>{for(const mutate of [f=>f.reviewPackages.clear(),f=>f.c.cycles[0].reviewPackageSha256='a'.repeat(64),f=>f.c.cycles[0].componentStates[0].contentSha256='b'.repeat(64),f=>f.c.cycles[0].reviewPackagePath='../private.json']){const f=fixture();mutate(f);fail(f,/package|component/i);}});
test('changed components advance every cycle and unchanged components preserve their prior revisions',()=>{pass(twoCycleFixture());pass(twoCycleFixture('practical'));});
test('retaining revision2 on a component changed again in cycle2 fails despite valid final baseline range and matching snapshot',()=>{for(const type of ['written','practical']){const f=twoCycleFixture(type);if(type==='written'){const o=f.bank.options.find(o=>o.optionId===f.q.links[1].optionId);o.revision=2;f.q.links[1].optionRevision=2;f.c.optionChanges=[change(o.optionId,baseline.options.find(x=>x.optionId===o.optionId),o)];}else{const o=f.q.parts[0].choices[1];o.revision=2;f.c.practicalChoiceChanges=[change(o.id,f.before.parts[0].choices[1],o)];}refresh(f);fail(f,/content changed without exactly one revision/);}});
test('unchanged component revision cannot advance artificially within reviewed cycles',()=>{const f=twoCycleFixture(),o=f.bank.options.find(o=>o.optionId===f.q.links[0].optionId),old=baseline.options.find(x=>x.optionId===o.optionId);o.revision=2;f.q.links[0].optionRevision=2;f.c.optionChanges.push(change(o.optionId,old,o));f.e.changedOptionIds.push(o.optionId);refresh(f);fail(f,/unchanged content revision/);});
test('ordinary round schema accepts historical PRD versions and new template records1.9 without rewriting prior ledger',()=>{const ordinary=JSON.parse(fs.readFileSync(new URL('../docs/rounds/round-ledger.schema.json',import.meta.url))),template=JSON.parse(fs.readFileSync(new URL('../docs/rounds/round-ledger.template.json',import.meta.url)));for(const v of ['1.7','1.8','1.9'])assert.deepEqual(validateJsonSchema({...clone(prior),prdVersion:v},ordinary),[]);assert.equal(template.prdVersion,'1.9');assert.equal(prior.prdVersion,'1.7');assert(validateJsonSchema({...clone(prior),prdVersion:'2.0'},ordinary).length);});
test('review package exact item allowlist rejects unregistered snapshots and raw-log payloads',()=>{for(const extra of [{correctionId:'unregistered-log',rawLog:'not an approved question snapshot'},{correctionId:'unregistered-snapshot',question:{questionId:'extra'},options:[]}]){const f=fixture(),cycle=f.c.cycles[0],p=JSON.parse(f.reviewPackages.get(cycle.reviewPackagePath).raw);p.items.push(extra);const raw=JSON.stringify(p);f.reviewPackages.set(cycle.reviewPackagePath,{raw});cycle.reviewPackageSha256=editorialHash(raw);fail(f,/allowlist|unapproved payload/);}});

test('seed-only manifest rollback cannot bypass latest cumulative history, even with a claimed successor record',()=>{const f=verifyFixture(fixture()),rawSeed=fs.readFileSync(new URL('../data/releases/2026.10.02-seed.4/bank.json',import.meta.url),'utf8'),seed=JSON.parse(rawSeed);f.banks.set(seed.bankVersion,{raw:rawSeed});const manifest={schemaVersion:1,bankVersion:seed.bankVersion,file:`releases/${seed.bankVersion}/bank.json`,releasedAt:seed.releasedAt,sha256:editorialHash(rawSeed),changeSummary:seed.changeSummary,finalRelease:false};const options={manifest,banks:f.banks,reviewPackages:f.reviewPackages,editorials:[f.e],now:Date.parse('2026-10-02T08:06:00Z')};assert.equal(validateReleaseLedger([], {manifest,banks:f.banks}).ok,true);for(const records of [[prior],[prior,{roundId:'claimed-seed-successor',startedAt:'2026-10-02T08:05:30Z',baseline:{bankVersion:f.bank.bankVersion,bankSha256:f.e.publication.bankSha256},publication:{status:'not_attempted',bankVersion:seed.bankVersion}}]]){const r=validateReleaseLedger(records,options);assert.equal(r.ok,false);assert.match(r.errors.join('\n'),/seed-only active bank|older than the latest verified/);}});
