/** Synthetic normal-root structures; no external delivery or publication claims. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {inspectNormalBackupRootProof,validateNormalBackupRootDependencies,proposeNormalBackupRootRegistration,prepareNormalBackupRoot} from '../scripts/normal-backup-root.mjs';
const root=path.resolve(import.meta.dirname,'..'),H=b=>createHash('sha256').update(b).digest('hex'),J=x=>JSON.stringify(x,null,2)+'\n',clone=structuredClone;
function fixture(){
 const oldCommit='1'.repeat(40),newCommit='2'.repeat(40),bankRaw=J({bankVersion:'synthetic.public'}),nextBank=J({bankVersion:'synthetic.delivered'}),oldManifest=J({bankVersion:'synthetic.public',file:'releases/synthetic.public/bank.json',sha256:H(bankRaw),finalRelease:false}),state=J({finalized:false});
 const source={roundId:'round-999',status:'closed',startedAt:'2026-10-07T11:00:00Z',closedAt:'2026-10-07T12:00:00Z',baseline:{sourceCommit:oldCommit,bankVersion:'synthetic.public',bankSha256:H(bankRaw)},publication:{status:'not_attempted',commit:null,verifiedAt:null,bankVersion:'synthetic.delivered',bankSha256:H(nextBank)}};
 function inv(files){return [...files].map(([path,raw])=>({path,sha256:H(raw),bytes:Buffer.byteLength(raw)})).sort((a,b)=>a.path.localeCompare(b.path));}
 function allow(files){files.set('PUBLICATION-MANIFEST.txt',[...new Set([...files.keys(),'PUBLICATION-MANIFEST.txt'])].sort().join('\n')+'\n');return files;}
 function anchor(files,baseCommit,observedAt){return {baseCommit,observedAt,manifestRaw:files.get('data/manifest.json'),publicationStateRaw:state,allowlistRaw:files.get('PUBLICATION-MANIFEST.txt'),remoteInventory:inv(files)};}
 const old=allow(new Map([['data/manifest.json',oldManifest],['data/publication-state.json',state],['data/releases/synthetic.public/bank.json',bankRaw]]));
 const remote=allow(new Map([...old,['docs/analysis/synthetic.md','Synthetic analysis only.\n']]));
 const nextManifest=J({bankVersion:'synthetic.delivered',file:'releases/synthetic.delivered/bank.json',sha256:H(nextBank),finalRelease:false});
 const delivered=allow(new Map([...old,['data/manifest.json',nextManifest],['data/releases/synthetic.delivered/bank.json',nextBank],['docs/rounds/round-999.json',J(source)]]));
 const before=new Map(inv(old).map(f=>[f.path,f])),files=inv(delivered),delta={schemaVersion:1,kind:'developer_patch_not_learner_import',deliveryMode:'release_backup',roundId:source.roundId,baseCommit:oldCommit,baseVerifiedAt:'2026-10-07T10:58:00Z',preparedAt:'2026-10-07T12:01:00Z',gitPublicationStatus:'not_attempted',publicationCommit:null,bankVersion:'synthetic.delivered',bankSha256:H(nextBank),newlyPublishedByPackaging:0,prerequisiteArtifacts:[],files:files.filter(f=>before.get(f.path)?.sha256!==f.sha256).map(f=>({...f,beforeSha256:before.get(f.path)?.sha256??null})),deletions:[]};
 const proof={schemaVersion:1,kind:'delivered_normal_release_root_checkpoint',roundId:source.roundId,deltaArtifactSha256:'a'.repeat(64),completeArtifactSha256:'b'.repeat(64),privateEvidence:{libraryReceiptSha256:'c'.repeat(64),attachmentReceiptSha256:'d'.repeat(64),uploadResultSha256:'e'.repeat(64),archiveAuditSha256:'f'.repeat(64),sourceCheckpointSha256:'1'.repeat(64),terminalEvidenceSha256:null},archiveVerifiedAt:'2026-10-07T12:02:00Z',attachmentAcceptedAt:'2026-10-07T12:03:00Z',verificationCompletedAt:'2026-10-07T15:00:00Z',newlyPublishedRegular:0,canPublish:false,userOpenOrDownloadObserved:false,sourceAnchor:anchor(old,oldCommit,delta.baseVerifiedAt),continuationAnchor:anchor(remote,newCommit,'2026-10-07T12:04:00Z'),anchorTransition:{parentCommit:oldCommit,evidenceSha256:'2'.repeat(64),changedPaths:inv(remote).filter(f=>before.get(f.path)?.sha256!==f.sha256).map(f=>({...f,beforeSha256:before.get(f.path)?.sha256??null}))},priorTrustSha256:null,preservedRegistries:[],deltaManifest:delta,completeManifest:{schemaVersion:1,kind:'complete_project_not_learner_import',deliveryMode:'release_backup',newlyPublishedRegular:0,projectDirectory:'project',prerequisiteArtifacts:[],sourceRelease:{roundId:source.roundId,deltaArtifactSha256:'a'.repeat(64),deltaManifestSha256:H(J(delta)),baseCommit:oldCommit,bankVersion:'synthetic.delivered',bankSha256:H(nextBank),ledgerPath:'docs/rounds/round-999.json',ledgerSha256:H(J(source))},frozenSourceInventory:clone(files),packagingRevision:null,files},runtimeManifestRaw:nextManifest,publicationStateRaw:state,sourceAllowlistRaw:delivered.get('PUBLICATION-MANIFEST.txt'),stoppedPublisher:null};
 return {proof,source,files:delivered,remote};
}
test('normal public root preserves source anchor separately from continuation anchor and admits no public count',()=>{
 const {proof,source}=fixture(),before=J(proof),base=inspectNormalBackupRootProof(proof,source);assert.equal(base.baseCommit,'2'.repeat(40));assert.equal(base.sourceBaseCommit,'1'.repeat(40));assert.equal(base.eligibleAt,proof.verificationCompletedAt);assert.equal(base.recordedAt,proof.attachmentAcceptedAt);assert.equal(J(proof),before);assert.equal(proof.savedAt,undefined);assert.equal(proof.origin,undefined);assert.equal(proof.deltaManifest.permissionNotifiedAt,undefined);
});
for(const [label,change,pattern] of [
 ['fake public count',p=>p.newlyPublishedRegular=4,/publication claim/],
 ['fake successful publication',p=>p.canPublish=true,/publication claim/],
 ['false user download',p=>p.userOpenOrDownloadObserved=true,/publication claim/],
 ['borrowed009 origin',p=>p.origin={},/fields/],
 ['synthetic savedAt',p=>p.savedAt='2026-10-07T12:03:00Z',/fields/],
 ['fabricated timeout',p=>p.deltaManifest.permissionNotifiedAt='2026-10-07T12:00:00Z',/fields/],
 ['download-only relabel',p=>p.deltaManifest.deliveryMode='download_only',/normal release pair/],
 ['wrong delta anchor',p=>p.deltaManifest.baseCommit='3'.repeat(40),/source anchor|identity/],
 ['foreign continuation parent',p=>p.anchorTransition.parentCommit='3'.repeat(40),/same public bank/],
 ['changed continuation bank',p=>p.continuationAnchor.manifestRaw+=' ',/marker mismatch/],
 ['same commit conflicting inventory',p=>p.continuationAnchor.baseCommit=p.sourceAnchor.baseCommit,/Same anchor commit/],
 ['omitted support diff',p=>p.anchorTransition.changedPaths.pop(),/before\/after/],
 ['delivered freeze',p=>p.runtimeManifestRaw=J({...JSON.parse(p.runtimeManifestRaw),finalRelease:true}),/source markers/],
 ['early current completion',p=>p.verificationCompletedAt='2026-10-07T12:02:00Z',/completed verification/],
 ['final cutoff',p=>p.verificationCompletedAt='2026-10-16T15:00:00Z',/cutoff/],
 ['invented prior trust',p=>p.priorTrustSha256='9'.repeat(64),/trust prefix/],
 ['delta before hash changed',p=>p.deltaManifest.files[0].beforeSha256='9'.repeat(64),/identity|reconstruct/]
])test('normal root rejects '+label,()=>{const {proof,source}=fixture();change(proof);assert.throws(()=>inspectNormalBackupRootProof(proof,source),pattern);});
test('normal root rejects offline successor relabeling and changed source decision',()=>{for(const patch of [{status:'open'},{publication:{status:'verified'}},{baseline:{offlinePredecessor:{roundId:'round-027'}}}]){const {proof,source}=fixture();Object.assign(source,patch);assert.throws(()=>inspectNormalBackupRootProof(proof,source),/closed unpublished/);}});
test('registration is a separate current timestamp, never a historical eligibility input',()=>{const {proof}=fixture(),before=Date.now(),registered=proposeNormalBackupRootRegistration(Buffer.from(J(proof))),after=Date.now();assert.ok(Date.parse(registered.trustRecord.registeredAt)>=before&&Date.parse(registered.trustRecord.registeredAt)<=after);assert.equal(registered.trustRecord.eligibleAt,registered.trustRecord.registeredAt);assert.equal(registered.trustRecord.sha256,H(J(proof)));assert.equal(proof.registeredAt,undefined);assert.throws(()=>proposeNormalBackupRootRegistration(Buffer.from(J({...proof,verificationCompletedAt:'2026-10-15T15:00:00Z'}))),/current registration/);});
test('private preparation refuses absent receipts, invented pair and future caller clock',async()=>{await assert.rejects(prepareNormalBackupRoot({}),/Exact original/);const empty=Buffer.from('{}'),args=Object.fromEntries(['deltaZip','completeZip','libraryReceiptRaw','attachmentReceiptRaw','uploadResultRaw','archiveAuditRaw','sourceCheckpointRaw','continuationEvidenceRaw'].map(k=>[k,empty]));await assert.rejects(prepareNormalBackupRoot({...args,now:Date.now()+60000}),/actual current/);await assert.rejects(prepareNormalBackupRoot(args),/original saved pair/);});
test('modern dependency loss and self-pinned registries are rejected without altering authority',async t=>{
 const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'normal-root-dependencies-'));t.after(()=>fs.rm(tmp,{recursive:true,force:true}));await fs.mkdir(path.join(tmp,'scripts'),{recursive:true});await fs.mkdir(path.join(tmp,'docs/deliveries'),{recursive:true});await fs.writeFile(path.join(tmp,'scripts/validate-round.mjs'),'loadNormalBackupRoots');await assert.rejects(validateNormalBackupRootDependencies(tmp),/Missing normal-root trust/);
 const registryPath=path.join(tmp,'docs/deliveries/normal-backup-root-trust.json');await fs.writeFile(registryPath,await fs.readFile(path.join(root,'docs/deliveries/normal-backup-root-trust.json')));await fs.writeFile(path.join(tmp,'PUBLICATION-MANIFEST.txt'),'scripts/normal-backup-root.mjs\ndocs/deliveries/normal-backup-root-trust.json\n');await fs.writeFile(path.join(tmp,'scripts/normal-backup-root.mjs'),'fixture dependency bytes');
 // No synthetic entry can become authority through the candidate's own file.
 const raw=JSON.parse(await fs.readFile(registryPath)),{proof}=fixture(),r=proposeNormalBackupRootRegistration(Buffer.from(J(proof)));raw.roots.push(r.trustRecord);await fs.writeFile(registryPath,J(raw));await assert.rejects(validateNormalBackupRootDependencies(tmp),/Unreviewed|duplicate|Reordered/);
});

test('isolated reviewed authority loads a root and fails closed for late or corrupted successors',async t=>{
 const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'normal-root-authority-'));t.after(()=>fs.rm(tmp,{recursive:true,force:true}));const write=async(p,raw)=>{await fs.mkdir(path.dirname(path.join(tmp,p)),{recursive:true});await fs.writeFile(path.join(tmp,p),raw);};
 for(const folder of ['scripts','src'])await fs.cp(path.join(root,folder),path.join(tmp,folder),{recursive:true});await write('package.json',await fs.readFile(path.join(root,'package.json')));
 for(const p of ['docs/deliveries/release-backup-trust.json','docs/deliveries/offline-chain-trust.json','docs/quarantines/trust.json','docs/release-blocks/trust.json'])await write(p,await fs.readFile(path.join(root,p)));
 const {proof,source,files,remote}=fixture(),proofRaw=Buffer.from(J(proof)),registeredAt=new Date().toISOString(),pin={roundId:proof.roundId,path:`docs/deliveries/normal-roots/${proof.roundId}.json`,sha256:H(proofRaw),sourceAnchorSha256:H(J(proof.sourceAnchor)),continuationAnchorSha256:H(J(proof.continuationAnchor)),registeredAt,eligibleAt:registeredAt},trust={schemaVersion:1,kind:'reviewed_normal_release_roots',roots:[pin]};
 for(const [p,raw]of files)await write(p,raw);await write('docs/analysis/synthetic.md',remote.get('docs/analysis/synthetic.md'));await write(pin.path,proofRaw);await write('docs/deliveries/normal-backup-root-trust.json',J(trust));
 const names=[...files.keys(),'docs/analysis/synthetic.md','scripts/normal-backup-root.mjs','scripts/validate-round.mjs','scripts/bank-io.mjs','docs/deliveries/normal-backup-root-trust.json',pin.path];await write('PUBLICATION-MANIFEST.txt',names.join('\n')+'\n');
 const api=await import(pathToFileURL(path.join(tmp,'scripts/normal-backup-root.mjs'))),context={now:Date.now(),manifest:{finalRelease:false},publicationState:{finalized:false},ledgers:[source],editorials:[],ledgerSources:new Map([[source.roundId,Buffer.from(J(source))]]),banks:new Map([['synthetic.delivered',{raw:Buffer.from(files.get('data/releases/synthetic.delivered/bank.json'))}]]),offlineBases:new Map(),deliveryCheckpointSources:new Map()};
 const loaded=await api.loadNormalBackupRoots(tmp,context);assert.equal(loaded.roots.size,1);assert.equal(loaded.offlineBases.get(proof.deltaArtifactSha256).baseCommit,proof.continuationAnchor.baseCommit);assert.equal(loaded.offlineBases.get(proof.deltaArtifactSha256).eligibleAt,pin.eligibleAt);assert.equal(context.offlineBases.size,0);assert.equal((await api.loadNormalBackupRoots(tmp,{...context,now:Date.parse(registeredAt)-1})).offlineBases.size,0);
 const snapshot=await Promise.all(names.map(async p=>({path:p,raw:await fs.readFile(path.join(tmp,p))})));assert.equal(api.validateNormalBackupRootSnapshot(snapshot).roots,1);
 for(const p of ['scripts/normal-backup-root.mjs','docs/deliveries/normal-backup-root-trust.json',pin.path])assert.throws(()=>api.validateNormalBackupRootSnapshot(snapshot.filter(f=>f.path!==p)),/dependency|proof/);
 const exact=loaded.offlineBases.get(proof.deltaArtifactSha256),successor={...source,roundId:'round-1000',startedAt:registeredAt,baseline:{sourceCommit:exact.baseCommit,bankVersion:exact.bankVersion,bankSha256:exact.bankSha256,offlinePredecessor:{artifactSha256:proof.deltaArtifactSha256,manifestSha256:exact.manifestSha256,ledgerSha256:exact.ledgerSha256,roundId:exact.roundId}}};
 const withSuccessor=l=>[...snapshot,{path:'docs/rounds/round-1000.json',raw:Buffer.from(J(l))}];assert.equal(api.validateNormalBackupRootSnapshot(withSuccessor(successor),{now:Date.now()}).roots,1);
 for(const mutate of [r=>r.startedAt=new Date(Date.parse(registeredAt)-1).toISOString(),r=>r.baseline.sourceCommit='9'.repeat(40),r=>r.baseline.bankSha256='9'.repeat(64),r=>r.baseline.offlinePredecessor.manifestSha256='9'.repeat(64)]){const r=clone(successor);mutate(r);assert.throws(()=>api.validateNormalBackupRootSnapshot(withSuccessor(r)),/exact registered predecessor/);}assert.throws(()=>api.validateNormalBackupRootSnapshot(withSuccessor(successor),{now:Date.parse(registeredAt)-1}),/eligible current chronology/);
 const bad=snapshot.map(f=>({...f}));bad.find(f=>f.path==='docs/deliveries/normal-backup-root-trust.json').raw=Buffer.from(J({...trust,roots:[]}));bad.push({path:'docs/rounds/round-1000.json',raw:Buffer.from(J({...source,roundId:'round-1000',startedAt:new Date(Date.parse(registeredAt)+1000).toISOString()}))});assert.throws(()=>api.validateNormalBackupRootSnapshot(bad),/later successor/);
 await assert.rejects(api.loadNormalBackupRoots(tmp,{...context,offlineBases:loaded.offlineBases}),/Duplicate/);
 await write('docs/rounds/round-999.json',J({...source,status:'running'}));await assert.rejects(api.loadNormalBackupRoots(tmp,context),/source|ledger/);await write('docs/rounds/round-999.json',J(source));
 await write('data/releases/synthetic.public/bank.json','tampered');await assert.rejects(api.loadNormalBackupRoots(tmp,context),/history/);await write('data/releases/synthetic.public/bank.json',files.get('data/releases/synthetic.public/bank.json'));
 await write('data/manifest.json',J({...JSON.parse(proof.runtimeManifestRaw),finalRelease:true}));await assert.rejects(api.loadNormalBackupRoots(tmp,context),/freeze/);await write('data/manifest.json',proof.runtimeManifestRaw);
 await write('docs/deliveries/normal-backup-root-trust.json',J({...trust,roots:[]}));await assert.rejects(api.loadNormalBackupRoots(tmp,{...context,ledgers:[source,{...source,roundId:'round-1000',startedAt:new Date(Date.parse(registeredAt)+1000).toISOString()}]}),/later successor/);
});
