import {APP_VERSION,SUBJECTS,copy,validateBank,isPublishedQuestion,eligibleQuestions,prepareSession,startSession,setAnswer,confirmAnswer,revealExplanation,finalize,extendTime,convertToUntimed,timeState,grade,isAnswered,sessionResult,statistics,createPrompt,adjustedResult,FREEZE_AT} from './domain.js';
import {openStore,updateBank,acquireEditor} from './storage.js';
import {exportBackup,partitionBackups,parseBackup,MAX_BACKUP_BYTES} from './backup.js';
const $=id=>document.getElementById(id);
const state={openGeneration:0,store:null,bank:null,bundle:null,sessions:[],session:null,editor:null,view:'home',queue:Promise.resolve(),storageFailed:false,unsaved:null,anchor:null,warningKeys:new Set(),settings:{timerWarnings:true}};
const subjectName=id=>SUBJECTS.find(s=>s.id===id)?.name||'웹접근성 실기중급';
const statusName={active:'진행 중',prepared:'시작 전',submitted:'최종 제출',expired:'시간 만료',abandoned:'중단',converted:'무제한 전환'};
const outcomeName={correct:'정답 / 만점',wrong:'오답 / 0점',partial:'부분점수',unanswered:'미응답'};
let saveNoticeTimer;
function announceSaved(){clearTimeout(saveNoticeTimer);saveNoticeTimer=setTimeout(()=>announce('답안과 진행 상태를 저장했습니다.'),700);}
const fmt=n=>n===null||n===undefined?'계산할 응답 없음':`${(n*100).toFixed(1)}%`;
const date=n=>new Date(n).toLocaleString('ko-KR');
function node(tag,attrs={},...children){const el=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')el.className=v;else if(k==='on')for(const[event,fn]of Object.entries(v))el.addEventListener(event,fn);else if(k==='text')el.textContent=v;else if(k==='value')el.value=v;else if(k==='checked'||k==='disabled'||k==='readOnly'||k==='hidden')el[k]=v;else if(v!==undefined&&v!==null)el.setAttribute(k,String(v));}for(const child of children.flat(Infinity))if(child!==null&&child!==undefined)el.append(child instanceof Node?child:document.createTextNode(String(child)));return el;}
function button(text,fn,opts={}){return node('button',{type:'button',...opts,on:{click:async event=>{try{await fn(event);}catch(error){showError(error);}}}},text);}
function actions(...children){return node('div',{class:'actions'},...children);}
function announce(message){clearTimeout(saveNoticeTimer);$('status').textContent='';requestAnimationFrame(()=>{$('status').textContent=message;});}
function showError(error){$('alert').replaceChildren(node('p',{},error.message||String(error)));if(error.code==='CONFLICT'&&state.session)$('alert').append(button('최신 저장 기록 다시 열기',()=>openSession(state.session.sessionId)));if(state.storageFailed){$('alert').append(node('p',{},'입력 변경을 잠시 막았습니다. 화면의 최신 입력을 긴급 백업한 뒤 저장을 다시 시도하세요.'),actions(button('미저장 입력 포함 긴급 백업',()=>emergencyBackup()),button('저장 다시 시도',retrySave)));$('alert').querySelector('button').textContent='미저장 입력 포함 긴급 백업';}}
function clearError(){$('alert').replaceChildren();}
function focusTitle(){queueMicrotask(()=>{$('view-title')?.focus();});}
function screen(title,...children){state.openGeneration++;state.view=title;document.title=`${title} · 웹접근성 2급 연습실`;$('main').replaceChildren(node('h2',{id:'view-title',tabindex:'-1'},title),...children.filter(child=>child!==null&&child!==undefined));focusTitle();}
function labelInput(label,input,help){const wrap=node('div',{},node('label',{for:input.id},label),input);if(help)wrap.append(node('p',{class:'muted',id:`${input.id}-help`},help));return wrap;}
function select(id,values,value){const el=node('select',{id});for(const [v,t]of values)el.append(node('option',{value:v},t));el.value=value;return el;}
function download(filename,text,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=node('a',{href:url,download:filename});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('파일 다운로드를 요청했습니다. 브라우저의 다운로드 목록을 확인하세요.');}
async function copyText(text,textarea=null){try{if(!navigator.clipboard?.writeText)throw new Error('clipboard unavailable');await navigator.clipboard.writeText(text);announce('클립보드에 복사했습니다.');}catch{announce('자동 복사가 되지 않았습니다. 텍스트를 선택한 뒤 Ctrl+C로 복사하거나 파일로 내려받으세요.');if(textarea){textarea.focus();textarea.select();}else showTextExport('수동 복사',text);}}
function showTextExport(title,text){const area=node('textarea',{id:'export-text',readOnly:true,rows:14},text);screen(title,node('p',{},'선택 가능한 전체 원문입니다. 줄바꿈과 특수문자를 보존하며 코드를 실행하지 않습니다.'),labelInput('전체 텍스트',area),actions(button('전체 선택',()=>{area.focus();area.select();}),button('복사',()=>copyText(text,area)),button('UTF-8 텍스트 내려받기',()=>download('접근성-연습-자료.txt',text)),button('문제로 돌아가기',()=>renderSession(),{class:'secondary'})));}
async function refreshSessions(){state.sessions=await state.store.sessions();return state.sessions;}
function nowState(s=state.session){return timeState(s,Date.now(),state.anchor?{...state.anchor,monoNow:performance.now()}:null);}
function edit(mutator,{render=false}={}){
  const task=async()=>{if(state.storageFailed)throw new Error('먼저 미저장 입력을 백업하거나 저장을 다시 시도하세요.');if(!state.session||state.session.status!=='active')throw new Error('진행 중 세션이 없습니다.');if(state.editor&&!state.editor.acquired)throw new Error('다른 탭에서 이 세션을 편집 중입니다. 다른 탭을 닫고 다시 열어 주세요.');clearError();const previous=state.session;let candidate;
    try{state.session=await state.store.update(previous.sessionId,previous.revision,s=>{const t=nowState(s);if(!t.trusted)s.clockTrusted=false;candidate=mutator(s,t.now);return candidate;});state.unsaved=null;if(state.session.status==='expired')announce('제한 시간이 끝나 저장된 답안으로 종료했습니다.');else announceSaved();if(state.session.status!=='active'){await refreshSessions();releaseEditor();renderResult(state.session);}else if(render)renderSession();}
    catch(error){if(error.name==='DomainError'){showError(error);}else if(error.code==='CONFLICT'){state.editor?.release();state.editor={acquired:false,release:()=>{}};$('alert').replaceChildren(node('p',{},error.message),button('최신 저장 기록 다시 열기',()=>openSession(previous.sessionId)));}else{state.storageFailed=true;state.unsaved=collectVisibleDraft(candidate||previous,previous);freezeAnswerInputs();showError(error);}throw error;}
  };const promise=state.queue.then(task);state.queue=promise.catch(()=>{});return promise;
}
function collectVisibleDraft(draft,previous){const originalAnswers=copy(draft.answers);const s=copy(draft),item=previous.items[previous.currentIndex];if(!item||!document.getElementById('view-title')?.textContent.startsWith('문항 '))return s;if(previous.attempts.some(a=>a.instanceId===item.instanceId))return s;if(item.type==='written'){const selected=document.querySelector('input[name="written-answer"]:checked');if(selected)s.answers[item.instanceId]=selected.value;}else{const answer={...(s.answers[item.instanceId]||{})};for(const p of item.parts){if(p.kind==='text'){const input=$(`part-${p.partId}`);if(input)answer[p.partId]=input.value;}else{const selected=[...document.querySelectorAll('input')].filter(el=>el.name===p.partId&&el.checked).map(el=>el.value);if(p.kind==='multi')answer[p.partId]=selected;else if(selected.length)answer[p.partId]=selected[0];}}if($('free-response'))answer.freeResponse=$('free-response').value;s.answers[item.instanceId]=answer;}if(s.status!=='active'||s.attempts.some(a=>a.instanceId===item.instanceId)){s.recoveryDraft={answers:copy(s.answers),observedAt:Date.now(),reason:'저장 실패 중 화면에 남은 입력',excludedFromGrade:true};s.answers=originalAnswers;}return s;}
function freezeAnswerInputs(){for(const el of $('main').querySelectorAll('input,textarea:not([readonly]),select'))el.disabled=true;}
async function retrySave(){if(!state.unsaved)return;try{let expired=false;state.session=await state.store.update(state.session.sessionId,state.session.revision,current=>{const t=nowState(current);expired=current.config.mode==='timed'&&t.expired;if(!expired)return state.unsaved;const result=finalize(current,'expired',t.now);result.recoveryDraft={answers:copy(state.unsaved.recoveryDraft?.answers||state.unsaved.answers),observedAt:Date.now(),reason:'마감 전 저장에 성공하지 못한 입력. 채점에서 제외하고 복구 자료로만 보존.',excludedFromGrade:true};return result;});state.storageFailed=false;state.unsaved=null;clearError();announce(expired?'제한 시간이 지나 마지막 저장 답안만으로 종료했습니다. 미저장 입력은 점수와 별도의 복구 초안으로 보존했습니다.':'미저장 입력을 저장했습니다.');renderSession();}catch(error){showError(error);}}
async function emergencyBackup(){const sessions=await state.store.sessions();if(state.unsaved){const i=sessions.findIndex(s=>s.sessionId===state.unsaved.sessionId);if(i<0)sessions.push(state.unsaved);else sessions[i]=state.unsaved;}showBackupDownloads(sessions,'긴급 백업 내보내기');}
function releaseEditor(){state.editor?.release();state.editor=null;state.anchor=null;}
async function leave(fn){state.openGeneration++;await state.queue;if(state.storageFailed){showError(new Error('저장이 실패한 입력이 있습니다. 긴급 백업하거나 저장을 다시 시도한 후 이동하세요.'));return;}releaseEditor();state.session=null;await fn();}
function installNavigation(){const nav=$('navigation');nav.replaceChildren(button('시작',()=>leave(renderHome)),button('오답 복습',()=>leave(()=>renderSetup('written',{pool:'wrong'}))),button('학습 기록',()=>leave(renderHistory)),button('문제 은행',()=>leave(renderBank)),button('백업 · 설정',()=>leave(renderManage)));}
async function renderHome(){await refreshSessions();const bank=state.bank;const active=state.sessions.filter(s=>s.status==='active');const intro=node('p',{},'필기와 실기를 짧은 묶음으로 연습합니다. 정답을 확정한 뒤 근거를 확인하거나, 시간을 정해 한 세트에 도전할 수 있습니다.');const cards=node('div',{class:'grid'},node('section',{class:'card'},node('h3',{},'필기 연습'),node('p',{},'5과목별 또는 전체 혼합 · 4/5지선다'),button('필기 설정하기',()=>renderSetup('written'),{disabled:!bank})),node('section',{class:'card'},node('h3',{},'실기 연습'),node('p',{},'구현 · 점검 · 미채점 서술 답안'),button('실기 설정하기',()=>renderSetup('practical'),{disabled:!bank})));
  const children=[intro,cards];if(active.length)children.push(node('h3',{},'이어 풀기'),node('ul',{class:'list-buttons'},active.map(s=>node('li',{},button(`${s.config.type==='written'?'필기':'실기'} ${s.config.mode==='timed'?'시간제':'무제한'} · ${s.items.length}문항 · ${date(s.startedAt)}`,()=>openSession(s.sessionId),{class:'secondary'})))));
  if(bank){const published=bank.questions.filter(q=>isPublishedQuestion(bank,q)),tests=published.filter(q=>q.testOnly).length;children.push(node('h3',{},'현재 연습 자료'),node('p',{},`공개 가능 문항 ${published.length}개 중 테스트 시드 ${tests}개. 테스트 기록은 일반 학습 통계와 분리하지만 각 세션의 점수와 해설을 확인할 수 있습니다.`),node('p',{class:'muted'},`문제 은행 ${bank.bankVersion} · 이 자료만으로 시험 전체 범위를 학습했다고 볼 수 없습니다.`));}
  else children.push(node('p',{},'문제 은행을 아직 읽지 못했습니다. 기록과 백업은 계속 사용할 수 있습니다.'),button('문제 은행 다시 확인',()=>checkUpdate(true)));
  screen('오늘의 연습',...children);
}
function renderSetup(type,overrides={}){if(!state.bank){showError(new Error('출제할 문제 은행이 없습니다. 업데이트를 다시 확인하세요.'));return;}clearError();const practical=type==='practical';const defaults={type,subjectId:practical?'practical':'all',mode:'untimed',kind:'practice',optionCount:5,count:practical?4:100,minutes:150,pool:'all',family:'all',feedbackAfter:'confirm',...overrides};
  const subject=select('subject',practical?[['practical','웹접근성 실기중급']]:[['all','전체 5과목 혼합'],...SUBJECTS.map(s=>[s.id,s.name])],defaults.subjectId);
  const kind=select('kind',[['practice','짧은 연습'],...(!practical?[['mock','100문항 모의시험 (학습 문항 확보 후)']]:[])],defaults.kind);
  const family=select('family',[['all','구현 + 점검 종합'],['implementation','웹페이지 구현'],['inspection','웹페이지 점검']],defaults.family);
  const mode=select('mode',[['untimed','무제한 학습'],['timed','시간제 연습']],defaults.mode);
  const count=node('input',{id:'count',type:'number',min:1,max:500,step:1,value:defaults.count,required:true,'aria-describedby':'setup-error availability'});
  const minutes=node('input',{id:'minutes',type:'number',min:1,max:1440,step:1,value:defaults.minutes,'aria-describedby':'setup-error'});
  const optionCount=select('option-count',[['5','5개'],['4','4개']],String(defaults.optionCount));
  const pool=select('pool',[['all','전체 문항'],['new','아직 확정하지 않은 학습 목표'],['wrong','이전에 오답·부분점수·미응답인 문항']],defaults.pool);
  const feedback=select('feedback',[['confirm','답 확정 후 해설 열기'],['end','세션 종료 후 해설 열기']],defaults.feedbackAfter);
  const availability=node('p',{id:'availability',class:'notice'}),error=node('p',{id:'setup-error',class:'error-help',role:'status'});
  const timeWrap=labelInput('제한 시간 (분)',minutes,'양의 정수 1~1440분. 편의 제공 시간이 있으면 여기에서 조정하세요.');
  const read=()=>({type,subjectId:subject.value,kind:kind.value,mode:mode.value,count:Number(count.value),minutes:Number(minutes.value),optionCount:Number(optionCount.value),pool:pool.value,family:family.value,feedbackAfter:feedback.value});
  function update(){const c=read(),eligible=eligibleQuestions(state.bank,c,state.sessions);const goals=new Set(eligible.map(q=>q.templateId)).size;availability.textContent=`지금 출제 가능한 서로 다른 문항: ${goals}개. 전체 혼합은 과목을 순환하며 균등하게 배분합니다. 원하는 수가 부족하면 아래 버튼으로 줄인 뒤 시작 안내를 확인하세요.`;timeWrap.hidden=mode.value!=='timed';minutes.disabled=mode.value!=='timed';feedback.disabled=mode.value==='timed';if(kind.value==='mock'){subject.value='all';subject.disabled=true;count.value=100;count.disabled=true;optionCount.value='5';optionCount.disabled=true;}else{subject.disabled=false;count.disabled=false;optionCount.disabled=false;}}
  for(const el of [subject,kind,family,mode,optionCount,pool])el.addEventListener('change',()=>{if(el===subject){minutes.value=subject.value==='all'?150:30;count.value=subject.value==='all'?100:20;}if(el===family)minutes.value=family.value==='all'?150:30;update();});
  const reduce=button('가능한 문항 수로 설정',()=>{const qs=eligibleQuestions(state.bank,read(),state.sessions);count.value=Math.max(1,new Set(qs.map(q=>q.templateId)).size);announce(`${count.value}문항으로 설정했습니다. 시작 전 안내를 확인하세요.`);update();},{class:'secondary'});
  const form=node('form',{on:{submit:event=>{event.preventDefault();clearError();error.textContent='';count.removeAttribute('aria-invalid');minutes.removeAttribute('aria-invalid');try{const config=read();const prepared=prepareSession(state.bank,config,state.sessions);renderStartPreview(prepared);}catch(e){error.textContent=e.message;const target=/시간/.test(e.message)?minutes:count;target.setAttribute('aria-invalid','true');target.focus();}}}},labelInput('연습 구성',kind),labelInput('과목',subject),...(practical?[labelInput('실기 과제군',family)]:[]),labelInput('시간 방식',mode),labelInput('문항 수',count),...(!practical?[labelInput('보기 수',optionCount)]:[]),timeWrap,labelInput('출제 범위',pool),labelInput('해설 공개 시점',feedback),availability,reduce,error,actions(node('button',{type:'submit'},'시작 전 안내 확인'),button('취소',renderHome,{class:'secondary'})));
  screen(practical?'실기 연습 설정':'필기 연습 설정',node('p',{},practical?'고정 답안은 문항별 규칙으로만 채점합니다. 자유 서술 답안은 미채점이며 자동 점수에 포함되지 않습니다.':'모의시험은 과목별 20개씩, 총 100개의 검토 완료 학습 문항이 필요합니다. 현재의 테스트 시드는 모의시험을 열지 않습니다.'),form);update();
}
function renderStartPreview(prepared){const config=prepared.config,counts={};for(const item of prepared.items)counts[item.subjectId]=(counts[item.subjectId]||0)+1;
  screen('시작 전 안내',node('p',{},`이번 세트: ${prepared.items.length}문항 · ${config.mode==='timed'?`시간제 ${config.minutes}분`:'무제한 학습'} · 문제 은행 ${prepared.bankVersion}`),node('ul',{},Object.entries(counts).map(([id,n])=>node('li',{},`${subjectName(id)} ${n}문항`))),node('p',{},config.mode==='timed'?'시작 버튼을 누르고 초기 저장에 성공한 후 시간이 흐릅니다. 탭 전환·절전·새로고침 동안에도 만료 시각은 유지됩니다. 종료 전 정답과 해설을 제공하지 않습니다.':'시간 제한이나 풀이 시간 통계가 없습니다. 답 선택은 임시 저장이며, 답 확정 버튼을 눌러야 풀이 이력이 됩니다.'),node('p',{class:'notice'},'테스트 시드 결과는 일반 학습 성과와 분리됩니다. 현재 문항의 실제 지문·보기 순서·해설·버전은 이 세션에 고정됩니다.'),node('p',{},'정적 앱의 데이터에서 정답을 찾을 수 있으므로 시험 감독이나 부정행위 방지 도구가 아닙니다.'),actions(button('연습 시작',async event=>{event.currentTarget.disabled=true;try{await state.store.insert(prepared);state.session=await state.store.update(prepared.sessionId,0,s=>startSession(s,Date.now()));await openSession(state.session.sessionId);announce('세션을 저장하고 연습을 시작했습니다.');}catch(e){event.currentTarget.disabled=false;showError(e);}}),button('설정으로 돌아가기',()=>renderSetup(config.type,config),{class:'secondary'})));
}
async function openSession(id){const generation=++state.openGeneration;await state.queue;if(generation!==state.openGeneration)return;releaseEditor();clearError();state.storageFailed=false;state.unsaved=null;const loaded=await state.store.session(id);if(generation!==state.openGeneration)return;if(!loaded)throw new Error('기록을 찾을 수 없습니다.');state.session=loaded;if(loaded.status!=='active'){renderResult(loaded);return;}
  const editor=await acquireEditor(id);if(generation!==state.openGeneration){editor.release();return;}state.editor=editor;if(!editor.acquired){screen('다른 탭에서 진행 중',node('p',{},'이 세션은 다른 탭이 편집하고 있습니다. 이 탭은 답을 덮어쓰지 않습니다. 기존 탭으로 돌아가거나 해당 탭을 닫은 뒤 다시 열어 주세요.'),actions(button('다시 열기',()=>openSession(id)),button('학습 기록',()=>leave(renderHistory),{class:'secondary'})));return;}
  const t=timeState(loaded,Date.now());if(!t.trusted||t.expired){const updated=await state.store.update(id,loaded.revision,s=>{s.clockTrusted=t.trusted;return t.expired?finalize(s,'expired',t.now):s;});if(generation!==state.openGeneration){editor.release();return;}state.session=updated;if(updated.status!=='active'){releaseEditor();await refreshSessions();if(generation!==state.openGeneration)return;renderResult(updated);announce('돌아온 시각에는 이미 제한 시간이 끝나 있었습니다. 원래 만료 시각으로 종료했습니다.');return;}}
  state.anchor={wall:Date.now(),mono:performance.now()};state.warningKeys=new Set(state.session.warnings||[]);renderSession();if(!state.session.clockTrusted)announce('시계 변경 또는 비정상 복귀가 감지되어 시간 신뢰를 낮게 표시합니다.');
}
function inputDisabled(item){return state.storageFailed||state.session.status!=='active'||state.session.attempts.some(a=>a.instanceId===item.instanceId);}
function renderMaterials(item){if(!item.materials?.length)return null;const wrapper=node('section',{'aria-label':'코드 자료'}),fileSelect=select('code-file',item.materials.map((m,i)=>[String(i),m.filename]),'0'),title=node('h3',{},'원본 코드'),area=node('textarea',{id:'source-code',class:'code',readOnly:true,spellcheck:'false',wrap:'off','aria-describedby':'code-help',rows:10}),help=node('p',{id:'code-help',class:'muted'},'코드는 안전한 텍스트로만 표시하며 실행하지 않습니다. 줄 번호는 복사되는 코드에 섞이지 않습니다.'),line=node('input',{id:'line-number',type:'number',min:1,value:1}),lineInfo=node('p',{id:'line-info',role:'status'}),newline=node('input',{id:'show-newlines',type:'checkbox'}),numbered=node('textarea',{id:'numbered-code',class:'code',readOnly:true,hidden:true,rows:8});
  const chosen=()=>item.materials[Number(fileSelect.value)];function update(){const m=chosen();area.value=m.content;const total=m.content.split('\n').length;title.textContent=`${m.filename} · ${total}줄`;line.max=total;line.value=1;lineInfo.textContent='';numbered.value=m.content.split('\n').map((text,index)=>`${index+1}: ${text} ↵`).join('\n');}
  const jump=(n)=>{const lines=chosen().content.split('\n');if(!Number.isInteger(n)||n<1||n>lines.length){lineInfo.textContent=`1~${lines.length} 사이의 줄 번호를 입력하세요.`;line.setAttribute('aria-invalid','true');line.focus();return;}line.removeAttribute('aria-invalid');const start=lines.slice(0,n-1).reduce((a,x)=>a+x.length+1,0);area.focus();area.setSelectionRange(start,start+lines[n-1].length);lineInfo.textContent=`${n}번째 줄을 선택했습니다: ${lines[n-1]}`;};fileSelect.addEventListener('change',()=>{update();announce(`${chosen().filename} 원문을 표시했습니다.`);});newline.addEventListener('change',()=>{numbered.hidden=!newline.checked;});
  wrapper.append(title,labelInput('코드 파일',fileSelect),labelInput('원본 코드 (읽기 전용)',area),help,actions(button('원본 코드 전체 복사',()=>copyText(chosen().content,area)),button('현재 과제 지시문 복사',()=>copyText(item.stem))),labelInput('이동할 줄 번호',line),actions(button('줄로 이동',()=>jump(Number(line.value))),button('과제 관련 구간으로 이동',()=>jump(chosen().focusLine||1))),lineInfo,node('label',{for:'show-newlines'},newline,'줄 번호와 줄바꿈 기호가 있는 별도 보기 표시'),labelInput('줄 번호·줄바꿈 보기 (원문 복사와 별도)',numbered));update();return wrapper;
}
function renderSession(){if(!state.session)return renderHome();if(state.session.status!=='active')return renderResult(state.session);const s=state.session,item=s.items[s.currentIndex],disabled=inputDisabled(item),attempt=s.attempts.find(a=>a.instanceId===item.instanceId);
  const heading=`문항 ${s.currentIndex+1} / ${s.items.length}: ${subjectName(item.subjectId)}`;const meta=node('p',{class:'progress'},`${item.questionId} · 개정판 ${item.revision} · ${item.testOnly?'테스트 시드':'검토 완료 학습 문항'} · ${s.config.mode==='timed'?'시간제':'무제한'}`);
  const children=[meta];if(s.config.mode==='timed'){const remaining=node('p',{id:'remaining',class:'badge','aria-live':'off'},remainingText(nowState(s).remaining));children.push(remaining,actions(button('남은 시간 확인',()=>announce(remainingText(nowState().remaining))),button('시간 연장',()=>renderExtend(),{class:'secondary'}),button('무제한으로 전환',()=>renderConvert(),{class:'secondary'})),node('p',{class:'muted'},'시간제 진행 중에는 정답·해설·AI 평가용 자료를 공개하지 않습니다.'));}
  const fieldset=node('fieldset',{},node('legend',{},item.stem));if(item.type==='written'){for(const[o,index]of item.options.map((o,i)=>[o,i])){const input=node('input',{id:`choice-${index}`,name:'written-answer',type:'radio',value:o.optionId,checked:s.answers[item.instanceId]===o.optionId,disabled});input.addEventListener('change',()=>{if(input.checked)edit((current,now)=>setAnswer(current,item.instanceId,o.optionId,now)).catch(()=>{});});fieldset.append(node('label',{class:'choice',for:input.id},input,node('span',{},`${index+1}. ${o.content}`)));}children.push(fieldset,renderMaterials(item));}
  else {children.push(node('p',{class:'answer-text'},item.stem),renderMaterials(item),node('p',{class:'muted'},'각 항목은 독립 채점합니다. 복수 선택은 정답 집합과 정확히 일치할 때만 해당 항목 만점입니다. 전체 자유 코딩의 의미를 자동 평가하지 않습니다.'));
    for(const part of item.parts){const fs=node('fieldset',{},node('legend',{},`${part.prompt} · ${part.points}점`)),answer=s.answers[item.instanceId]?.[part.partId];
      const save=value=>edit((current,now)=>setAnswer(current,item.instanceId,{...(current.answers[item.instanceId]||{}),[part.partId]:value},now)).catch(()=>{});
      if(part.kind==='text'){const input=node('input',{id:`part-${part.partId}`,type:'text',value:answer||'',disabled,maxlength:10000,'aria-describedby':`rule-${part.partId}`});input.addEventListener('input',()=>save(input.value));fs.append(labelInput('빈칸 답',input),node('p',{id:`rule-${part.partId}`,class:'muted'},part.normalization==='trim'?'앞뒤 공백만 무시합니다. 대소문자와 내부 공백은 그대로 비교합니다.':'공백과 대소문자까지 정확히 비교합니다.'));}
      else for(const[c,i]of part.choices.map((c,i)=>[c,i])){const inp=node('input',{id:`${part.partId}-${i}`,name:part.partId,type:part.kind==='multi'?'checkbox':'radio',value:c.id,checked:part.kind==='multi'?Array.isArray(answer)&&answer.includes(c.id):answer===c.id,disabled});inp.addEventListener('change',()=>{if(part.kind==='multi')save([...fs.querySelectorAll('input:checked')].map(e=>e.value));else if(inp.checked)save(inp.value);});fs.append(node('label',{class:'choice',for:inp.id},inp,node('span',{class:'answer-text'},`${i+1}. ${c.text}`)));}children.push(fs);
    }
    const free=node('textarea',{id:'free-response',rows:8,disabled,maxlength:1000000},s.answers[item.instanceId]?.freeResponse||'');free.addEventListener('input',()=>edit((current,now)=>setAnswer(current,item.instanceId,{...(current.answers[item.instanceId]||{}),freeResponse:free.value},now)).catch(()=>{}));children.push(node('h3',{},'서술형 답안 연습 · 미채점'),node('p',{},item.freeResponsePrompt),labelInput('자유 서술 답안',free,'자동 정답률·점수에 포함되지 않습니다. 실제 업무 정보나 개인정보를 입력하지 마세요.'),actions(button('AI 평가용 프롬프트 만들기',()=>renderPrompt(item),{disabled:s.config.mode==='timed',class:'secondary'})));
  }
  if(s.config.mode==='untimed'){if(!attempt)children.push(actions(button('답 확정',()=>edit((current,now)=>confirmAnswer(current,item.instanceId,now),{render:true}))));else{children.push(node('p',{class:'badge'},`답 확정 완료: ${outcomeName[attempt.grade.status]}`));if(s.config.feedbackAfter!=='end'){children.push(button('해설 열기',()=>edit(current=>revealExplanation(current,item.instanceId),{render:true}),{class:'secondary'}));if(s.revealed[item.instanceId])children.push(renderExplanation(item,s.answers[item.instanceId]));}else children.push(node('p',{},'해설은 세션을 종료한 뒤 확인할 수 있습니다.'));}}
  const flag=node('input',{id:'flag-question',type:'checkbox',disabled:state.storageFailed,checked:!!s.flags[item.instanceId]});flag.addEventListener('change',()=>edit(current=>{current.flags[item.instanceId]=flag.checked;return current;}).catch(()=>{}));children.push(node('label',{for:'flag-question'},flag,'나중에 다시 보기 표시'),actions(button('이전 문항',()=>moveQuestion(s.currentIndex-1),{disabled:s.currentIndex===0,class:'secondary'}),button('다음 문항',()=>moveQuestion(s.currentIndex+1),{disabled:s.currentIndex===s.items.length-1}),button('문제 목록',renderQuestionList,{class:'secondary'})),actions(button('세션 종료',()=>renderFinish(),{class:'secondary'})));
  screen(heading,...children.filter(Boolean));
}
async function moveQuestion(index){await edit(current=>{if(index>=0&&index<current.items.length)current.currentIndex=index;return current;},{render:true});}
function renderQuestionList(){const s=state.session;screen('문제 목록',node('p',{},'현재 답은 임시 저장됩니다. 문항을 선택하면 그 문항 제목으로 이동합니다.'),node('ol',{class:'list-buttons'},s.items.map((item,i)=>node('li',{},button(`${i+1}. ${subjectName(item.subjectId)} · ${s.attempts.some(a=>a.instanceId===item.instanceId)?'확정':isAnswered(item,s.answers[item.instanceId])?'응답 있음':'미응답'}${s.flags[item.instanceId]?' · 다시 보기 표시':''}`,()=>moveQuestion(i),{class:'secondary'})))),button('현재 문항으로 돌아가기',renderSession));}
function renderExplanation(item,answer){const result=grade(item,answer);const box=node('section',{class:'feedback'},node('h3',{},`해설 · ${outcomeName[result.status]}`),node('p',{},item.explanation));if(item.type==='written'){box.append(node('p',{},`정답: ${item.options.find(o=>o.optionId===item.correctOptionId)?.content}`),node('ol',{},item.options.map(o=>node('li',{},node('strong',{},`${o.content} · ${o.optionId===item.correctOptionId?'정답 보기':'오답 보기'}`),node('p',{},`공통 해설: ${o.explanation}`),node('p',{},`이 문제에서: ${o.contextExplanation}`)))));}else{box.append(node('p',{},`고정 답안 점수 ${result.points} / ${result.maxPoints}점. 자유 서술은 미채점입니다.`),node('ul',{},item.parts.map(p=>node('li',{},node('strong',{},`${p.prompt} · ${result.parts.find(g=>g.partId===p.partId).points}/${p.points}점`),node('p',{},`허용 답: ${p.kind==='text'?p.accepted.map(x=>JSON.stringify(x)).join(' 또는 '):p.correct.map(id=>p.choices.find(c=>c.id===id).text).join(' / ')}`),node('p',{},p.explanation)))),node('h4',{},'참고 서술 답안'),node('p',{class:'answer-text'},item.referenceAnswer));}
  box.append(node('p',{class:'muted'},`적용 기준: ${item.standardVersion} · 예상 난도: ${item.difficulty}`),node('h4',{},'근거'),node('ul',{},item.sources.map(source=>node('li',{},node('a',{href:source.url,target:'_blank',rel:'noopener noreferrer'},`${source.title} (새 탭)`),node('p',{},`${source.version} · ${source.location} · 확인 ${source.checkedAt}`),node('p',{},source.evidence)))));return box;
}
function renderFinish(){const s=state.session,answered=s.items.filter(item=>isAnswered(item,s.answers[item.instanceId])).length,confirmed=s.attempts.length;screen('세션 종료 확인',node('p',{},`전체 ${s.items.length}문항 중 응답 ${answered}문항, 미응답 ${s.items.length-answered}문항${s.config.mode==='untimed'?`, 확정 ${confirmed}문항`:''}입니다.`),node('p',{},s.config.mode==='timed'?'최종 제출하면 미응답을 포함하여 채점합니다. 중단은 완료 성적과 최초 시도 성과에 포함되지 않습니다.':'확정한 풀이만 학습 이력에 남습니다. 확정하지 않은 임시 답안은 보존되며 최종 결과에서 미확정으로 구분됩니다.'),actions(button('최종 제출하고 결과 보기',()=>edit((current,now)=>finalize(current,'submitted',now))),button('중단하고 답안 보존',()=>edit((current,now)=>finalize(current,'abandoned',now)),{class:'danger'}),button('계속 풀기',renderSession,{class:'secondary'})));}
function renderExtend(){const input=node('input',{id:'extend-minutes',type:'number',min:1,max:1440,value:10});screen('제한 시간 연장',node('p',{},'진행 중에도 시간은 계속 흐릅니다. 연장 사실을 기록하고 공식 구성 모의 기준과 구분합니다.'),labelInput('추가할 시간 (분)',input),actions(button('연장 적용',()=>edit((s,now)=>extendTime(s,Number(input.value),now),{render:true})),button('취소',renderSession,{class:'secondary'})));}
function renderConvert(){screen('무제한 학습으로 전환',node('p',{},'현재 시간제는 전환 상태로 종료하며 시간제 성적을 만들지 않습니다. 임시 답안을 새 무제한 세션으로 넘깁니다. 이후 확정한 답은 도움 허용 연습으로 분리됩니다.'),actions(button('전환하고 계속 풀기',async()=>{await state.queue;const previous=state.session;const converted=await state.store.convert(previous.sessionId,previous.revision,s=>convertToUntimed(s,crypto.randomUUID(),nowState(s).now));await openSession(converted.next.sessionId);announce('답안을 보존하고 무제한 학습으로 전환했습니다.');}),button('취소',renderSession,{class:'secondary'})));}
function answerSummary(item,answer){if(item.type==='written')return item.options.find(o=>o.optionId===answer)?.content||'미응답';return item.parts.map(p=>`${p.prompt}: ${p.kind==='text'?(answer?.[p.partId]||'미응답'):p.kind==='multi'?(answer?.[p.partId]||[]).map(id=>p.choices.find(c=>c.id===id)?.text||id).join(' / ')||'미응답':p.choices.find(c=>c.id===answer?.[p.partId])?.text||'미응답'}`).join('\n');}
async function renderResult(s){state.session=s;const result=s.result||sessionResult(s),completed=['submitted','expired'].includes(s.status);const children=[node('p',{},`${s.config.type==='written'?'필기':'실기'} · ${s.config.mode==='timed'?'시간제':'무제한'} · 종료: ${statusName[s.status]}`),node('p',{},`문제 은행 ${s.bankVersion} · 시작 ${date(s.startedAt||s.createdAt)}`)];
  if(s.recoveryDraft)children.push(node('p',{class:'notice'},'저장 실패 당시 입력을 별도 복구 초안으로 보존했습니다. 이 초안은 마감 전에 저장되지 않아 점수에 포함하지 않았습니다.'),button('미채점 복구 초안 내려받기',()=>download('접근성-미채점-복구초안.json',JSON.stringify(s.recoveryDraft,null,2),'application/json')));
  if(s.items.some(q=>q.testOnly))children.push(node('p',{class:'notice'},'테스트 시드가 포함된 세션입니다. 아래 결과와 해설은 기능 확인용이며 일반 학습 성과에 합산되지 않습니다.'));
  if(!completed)children.push(node('p',{},s.status==='converted'?'이 시간제는 무제한으로 전환했습니다. 시간제 성적을 만들지 않았습니다.':'세션을 중단했습니다. 임시 답안을 보존했으며 완료 성적으로 계산하지 않습니다.'));
  else {children.push(node('h3',{},'결과 요약'),node('p',{},`전체 ${result.total}문항 · 정답/만점 ${result.correct} · 오답/0점 ${result.wrong} · 부분점수 ${result.partial} · 미응답 ${result.unanswered}`));if(s.config.mode==='untimed')children.push(node('p',{},`명시적으로 확정한 풀이 ${s.attempts.length}개, 미확정 ${result.unconfirmed}개. 미확정 문항은 세트 결과에서 미응답으로 처리하고 학습 시도 통계에는 넣지 않습니다.`));children.push(node('p',{},`응답한 문항의 정답률 ${fmt(result.accuracy)} (정답 ${result.correct} / 실제 응답 ${result.answered})`),node('p',{},`전체 채점 대상 기준 점수 ${fmt(result.score)} (${result.points} / ${result.maxPoints}점)`));if(s.config.type==='practical')children.push(node('p',{},'자유 서술 답안은 모두 미채점입니다. 고정 답안형의 점수로 실제 서술 능력이나 공식 합격을 판단하지 않습니다.'));children.push(node('h3',{},'과목별 결과'),node('ul',{},Object.entries(result.bySubject).map(([id,r])=>node('li',{},`${subjectName(id)}: 정답/만점 ${r.correct}, 오답/0점 ${r.wrong}, 부분점수 ${r.partial}, 미응답 ${r.unanswered} · ${r.points}/${r.maxPoints}점`))));if(result.mockEligible)children.push(node('p',{class:'notice'},`앱 모의 기준 ${result.mockMet?'충족':'미충족'}: 과목별 40점 이상과 평균 60점 이상을 함께 확인합니다. 공식 합격 판정은 아닙니다.`));}
  if(s.config.mode==='timed')children.push(node('p',{},`설정 제한 시간 ${s.config.minutes}분 · 수행 시간 ${Math.round((s.elapsedMs||0)/1000)}초 · 종료 이유 ${statusName[s.status]}`),node('p',{class:'muted'},s.status==='expired'?`만료 시각 ${date(s.expiresAt)} · 실제 확인 시각 ${date(s.observedAt)}`:''),node('p',{class:'muted'},s.clockTrusted?'시간 기록 신뢰: 정상 범위. 브라우저 시계 기반이며 공식 시험 시계가 아닙니다.':'시계 이상 감지: 시간 신뢰 낮음. 속도 통계에서 제외합니다.'),...(s.timingChanges.length?[node('p',{},'연습 도중 시간 설정을 변경했습니다. 공식 구성 모의 기준과 구분합니다.')]:[]));
  children.push(node('h3',{},'문항별 답안과 해설'),node('ol',{class:'list-buttons'},s.items.map((item,i)=>{const a=s.attempts.find(a=>a.instanceId===item.instanceId);return node('li',{},button(`${i+1}. ${subjectName(item.subjectId)} · ${a?outcomeName[a.grade.status]:'미확정 / 미채점'}${s.revealed[item.instanceId]?' · 해설 열람':''}`,()=>renderReview(s,item),{class:'secondary'}));})),actions(button('같은 범위 다시 연습',()=>leave(()=>renderSetup(s.config.type,{...s.config,pool:'all',kind:'practice'}))),button('오답 복습 설정',()=>leave(()=>renderSetup(s.config.type,{...s.config,pool:'wrong',kind:'practice',mode:'untimed',count:1})),{class:'secondary'}),button('학습 기록으로',()=>leave(renderHistory),{class:'secondary'})));
  screen('학습 결과',...children);const corrections=state.bank?.corrections||[];if(corrections.length){const adjusted=await adjustedResult(s,corrections);if(state.session?.sessionId===s.sessionId&&state.view==='학습 결과'&&adjusted.changes.length)$('main').append(node('section',{class:'notice'},node('h3',{},'현재 기준 조정 결과'),node('p',{},`당시 결과는 위에 보존했습니다. 현재 기준에서 ${adjusted.excluded}문항 제외, ${adjusted.result.points}/${adjusted.result.maxPoints}점입니다.`),node('ul',{},adjusted.changes.map(c=>node('li',{},c.reason)))));}
}
async function renderReview(s,item){if(!s.revealed[item.instanceId])s=await state.store.update(s.sessionId,s.revision,current=>revealExplanation(current,item.instanceId));state.session=s;await refreshSessions();const answer=s.answers[item.instanceId];screen(`문항 해설: ${item.questionId}`,node('p',{},`${item.testOnly?'테스트 시드':'학습 문항'} · 당시 개정판 ${item.revision} · 은행 ${s.bankVersion}`),node('p',{class:'answer-text'},item.stem),renderMaterials(item),node('h3',{},'저장된 사용자 답안'),node('p',{class:'answer-text'},answerSummary(item,answer)),...(item.type==='practical'?[node('h3',{},'자유 서술 답안 · 미채점'),node('p',{class:'answer-text'},answer?.freeResponse||'작성하지 않았습니다.')]:[]),renderExplanation(item,answer),...(item.type==='practical'?[button('AI 평가용 프롬프트 만들기',()=>renderPrompt(item))]:[]),actions(button('결과로 돌아가기',()=>renderResult(s),{class:'secondary'})));}
async function renderPrompt(item){const s=state.session;if(s.config.mode==='timed'&&s.status==='active')throw new Error('시간제 종료 후 사용할 수 있습니다.');if(s.status==='active')await edit(current=>{current.exported[item.instanceId]=true;current.exposureEvents??=[];current.exposureEvents.push({key:`${item.templateId}@${item.learningGoalRevision}`,kind:'prompt',at:Date.now()});return current;});
  const format=select('prompt-format',[['reference','기준 비교용: 참고 정답과 평가 기준 포함'],['independent','독립 평가용: 참고 정답·평가 기준 미포함']],'reference'),blank=node('input',{id:'blank-answer',type:'checkbox'}),area=node('textarea',{id:'prompt-preview',readOnly:true,rows:18});
  const update=()=>{area.value=createPrompt(state.session,item,{includeReference:format.value==='reference',blank:blank.checked});};format.addEventListener('change',update);blank.addEventListener('change',update);update();screen('AI 평가용 프롬프트 미리보기',node('p',{class:'notice'},'앱은 AI에 전송하지 않습니다. 외부 서비스에 붙여 넣기 전에 개인정보·회사 정보·비밀키·비공개 코드를 제거하세요. AI의 판단은 참고이며 공식 점수에 합산하지 않습니다.'),node('p',{},'독립 평가가 필요하면 정답 미포함 버전을 별도 대화에서 먼저 사용하세요. 정답 포함 프롬프트 안의 지시만으로 블라인드 평가를 보장할 수 없습니다.'),labelInput('평가 자료 구성',format),node('label',{for:'blank-answer'},blank,'현재 답안 대신 빈 답안 영역 넣기'),labelInput('전체 프롬프트 (누락 없이 미리보기)',area),actions(button('프롬프트 복사',()=>copyText(area.value,area)),button('전체 선택 (수동 복사)',()=>{area.focus();area.select();}),button('프롬프트 텍스트 내려받기',()=>download(`${item.questionId}-AI-연습.txt`,area.value)),button('돌아가기',()=>state.session.status==='active'?renderSession():renderReview(state.session,item),{class:'secondary'})));
}
async function renderHistory(){await refreshSessions();const mode=select('stats-mode',[['untimed','무제한'],['timed','시간제']],'untimed'),type=select('stats-type',[['written','필기'],['practical','실기']],'written'),test=select('stats-test',[['false','일반 학습 기록'],['true','테스트 시드 기록']],'false'),stats=node('section',{id:'statistics'});
  const update=()=>{const st=statistics(state.sessions,{mode:mode.value,type:type.value,testOnly:test.value==='true',corrections:state.bank?.corrections||[]});stats.replaceChildren(node('h3',{},'선택 범위의 최초 시도'),node('p',{},`${st.first.count}건 · 정답/만점 ${st.first.correct}, 오답/0점 ${st.first.wrong}, 부분점수 ${st.first.partial}, 미응답 ${st.first.unanswered} · 응답 정답률 ${fmt(st.first.accuracy)}`),node('p',{},`재시도 ${st.retries.count}건 · 재시도 정답률 ${fmt(st.retries.accuracy)}. 도움을 열었거나 무제한으로 전환한 기록 ${st.assisted}건은 최초 성과에서 제외합니다.`),node('p',{},`학습한 고유 문항 ${st.uniqueQuestions}개 · 고유 학습 목표 ${st.uniqueGoals}개. 무효 정정으로 제외한 풀이 ${st.invalidExcluded}개. 보기 순서 변경은 새로운 지식 문항으로 세지 않습니다.`),node('h4',{},'과목별 최초 시도'),node('ul',{},Object.entries(st.bySubject).map(([id,r])=>node('li',{},`${subjectName(id)}: ${r.correct}/${r.answered} 응답 정답, 미응답 ${r.unanswered} · ${fmt(r.accuracy)}`))),node('h4',{},'주제별 최초 시도'),node('ul',{},Object.entries(st.byTopic).map(([topic,r])=>node('li',{},`${topic}: ${r.correct}/${r.answered} 응답 정답 · ${fmt(r.accuracy)}`))),node('h4',{},'최근 확정 풀이'),st.recent.length?node('ul',{},st.recent.map(a=>node('li',{},`${a.questionId} · ${outcomeName[a.grade.status]} · ${date(a.confirmedAt)}${a.exportedBefore?' · 확정 전 평가 자료 열람':''}`))):node('p',{},'선택한 범위에 기록이 없습니다. 테스트 시드 기록 보기를 선택하면 첫날 연습 결과를 볼 수 있습니다.'));
  };for(const el of[mode,type,test])el.addEventListener('change',update);screen('학습 기록',node('p',{},'최초 시도는 같은 학습 목표와 개정판을 기준으로 한 번만 집계합니다. 시간제와 무제한, 테스트 시드와 일반 학습, 자유 서술 답안을 섞지 않습니다.'),node('div',{class:'grid'},labelInput('시간 방식',mode),labelInput('문제 유형',type),labelInput('콘텐츠 분류',test)),stats,node('h3',{},'세션 이력'),state.sessions.length?node('ul',{class:'list-buttons'},[...state.sessions].sort((a,b)=>b.createdAt-a.createdAt).map(s=>node('li',{},button(`${date(s.startedAt||s.createdAt)} · ${s.config.type==='written'?'필기':'실기'} ${s.config.mode==='timed'?'시간제':'무제한'} · ${s.items.length}문항 · ${statusName[s.status]}`,()=>openSession(s.sessionId),{class:'secondary'})))):node('p',{},'아직 저장된 세션이 없습니다.'));update();
}
async function checkUpdate(show=true){clearError();try{const previous=state.bank?.bankVersion;state.bundle=await updateBank(state.store,new URL('./',document.baseURI));state.bank=state.bundle.bank;$('version').textContent=`앱 ${APP_VERSION} · 문제 은행 ${state.bank.bankVersion}`;announce(previous===state.bank.bankVersion?'최신 문제 은행을 확인했습니다. 현재 버전을 유지합니다.':'새 문제 은행을 검증하여 저장했습니다. 새 세션부터 적용하며 기존 세션은 그대로입니다.');if(show)renderBank();}catch(error){showError(error);if(!state.bank&&show)renderBank();}}
function renderBank(){const bank=state.bank;const children=[node('p',{},`앱 버전 ${APP_VERSION}. 문제 은행은 전체 파일의 SHA-256·구조·버전을 확인한 뒤 한 번에 적용합니다.`),button('업데이트 확인',()=>checkUpdate(true))];if(bank){const counts=SUBJECTS.map(s=>({name:s.name,all:bank.questions.filter(q=>q.subjectId===s.id&&isPublishedQuestion(bank,q)).length,learning:bank.questions.filter(q=>q.subjectId===s.id&&isPublishedQuestion(bank,q)&&!q.testOnly).length}));children.push(node('h3',{},`현재 문제 은행 ${bank.bankVersion}`),node('p',{},`콘텐츠 릴리스 준비 시각 ${bank.releasedAt} · 출제기준 ${bank.syllabusVersion}`),node('p',{},state.bundle?.manifest?.finalRelease?'최종 동결 버전입니다. 새 문항의 정기 누적은 종료되었으며 학습은 계속할 수 있습니다.':'문제 은행 누적 기간의 미리보기입니다.'),node('p',{},`마지막 업데이트 확인 ${state.bundle?.checkedAt?date(state.bundle.checkedAt):'확인 기록 없음'}`),node('p',{},bank.changeSummary),node('ul',{},counts.map(c=>node('li',{},`${c.name}: 출제 가능 ${c.all}개, 일반 학습용 ${c.learning}개`))),node('p',{},`실기 출제 가능 ${bank.questions.filter(q=>q.type==='practical'&&isPublishedQuestion(bank,q)).length}개`),node('p',{class:'notice'},'100문항 모의시험은 과목마다 서로 다른 검토 완료 일반 학습 문항 20개가 필요합니다. 테스트 시드와 보기 조합 수는 여기에 포함하지 않습니다.'),node('h3',{},'갱신 마감'),node('p',{},`2026년 10월 17일 00:00 (대한민국 표준시), ${new Date(FREEZE_AT).toISOString()}. 공개 직전 마감 검사를 통과해야 새 문항을 배포합니다. 마감 전에 공개된 최종 파일은 마감 후에도 내려받고 학습할 수 있습니다.`),node('p',{},'이 정적 앱 자체가 인터넷을 조사하거나 문항을 생성하지 않습니다. 외부의 조사·검토·배포 절차에서 검증된 파일만 받습니다.'),node('h3',{},'출처와 권리'),node('ul',{},bank.sources.map(s=>node('li',{},node('a',{href:s.url,target:'_blank',rel:'noopener noreferrer'},`${s.title} (새 탭)`),node('p',{},`${s.version} · ${s.location} · 확인 ${s.checkedAt}`),node('p',{class:'muted'},s.rights)))));}else children.push(node('p',{},'검증된 문제 은행이 없습니다. 네트워크와 배포 파일을 확인해 주세요.'));screen('문제 은행 정보',...children);}
function showBackupDownloads(sessions,title='기록 백업 내보내기'){const parts=partitionBackups(sessions);if(parts.length===1&&parts[0].restorable){download(parts[0].filename,parts[0].content,'application/json');return;}screen(title,node('p',{},`전체 ${sessions.length}세션을 ${parts.length}개 파일로 나눴습니다. 각 버튼을 눌러 개별 파일을 내려받으세요. 자동으로 여러 다운로드를 시작하지 않습니다.`),node('p',{},'복원 가능한 파일은 각각 10MB 이하·1000세션 이하입니다. 모든 파일을 차례로 합치기 방식으로 가져오면 됩니다. 세션 ID를 보존하며 이미 가져온 기록은 중복 추가하지 않습니다.'),...parts.map((part,index)=>node('section',{class:part.restorable?'card':'notice'},node('h3',{},`파일 ${index+1} / ${parts.length}: ${part.restorable?'복원 가능한 백업':'원문 보존 전용 · 현재 앱으로 복원 불가'}`),node('p',{},`${part.sessionCount}세션 · ${(part.byteLength/1024/1024).toFixed(2)}MB`),node('p',{},part.reason),button(part.restorable?`${index+1}번 백업 내려받기`:`${index+1}번 원문 보존 파일 내려받기 (가져오기 불가)`,()=>download(part.filename,part.content,'application/json')))),actions(button(state.storageFailed?'미저장 문제로 돌아가기':'백업 설정으로 돌아가기',()=>state.storageFailed?renderSession():renderManage(),{class:'secondary'})));}

async function renderManage(){await refreshSessions();const file=node('input',{id:'backup-file',type:'file',accept:'.json,application/json'}),importMode=select('import-mode',[['merge','합치기: 중복·충돌 ID는 기존 기록 유지'],['replace','교체: 현재 세션 이력을 모두 대체']],'merge'),warnings=node('input',{id:'timer-warning-setting',type:'checkbox',checked:state.settings.timerWarnings});warnings.addEventListener('change',async()=>{state.settings.timerWarnings=warnings.checked;try{await state.store.putMeta('settings',state.settings);announce('타이머 알림 설정을 저장했습니다.');}catch(e){showError(e);}});
  const importButton=button('파일 검사 후 가져오기',async()=>{const selected=file.files[0];if(!selected)throw new Error('먼저 JSON 백업 파일을 선택하세요.');if(selected.size>MAX_BACKUP_BYTES)throw new Error('백업 파일은 최대 10MB입니다.');const parsed=parseBackup(await selected.text()),replace=importMode.value==='replace';if(replace&&!window.confirm(`현재 ${state.sessions.length}개 세션을 삭제하고 파일의 ${parsed.sessions.length}개 세션으로 교체합니다. 백업하지 않은 기존 기록을 잃습니다. 계속할까요?`))return;const result=await state.store.importSessions(parsed.sessions,replace);await refreshSessions();announce(`${result.imported}세션을 가져왔습니다. 동일 기록 ${result.duplicates}개, 내용이 다른 중복 ID ${result.conflicts}개는 기존 기록을 유지했습니다.`);});
  screen('백업과 설정',node('h3',{},'내보내기'),node('p',{},'기록 파일에는 사용자 답안과 서술 내용이 들어갑니다. 개인정보나 회사 자료가 있다면 다른 사람에게 공유하기 전에 확인하세요.'),actions(button('전체 기록 JSON 내려받기',async()=>{await refreshSessions();showBackupDownloads(state.sessions);})),node('h3',{},'가져오기'),node('p',{},'UTF-8 JSON, 최대 10MB·1000세션. 모든 문항 스냅샷과 채점 결과를 먼저 검증합니다. 잘못된 파일은 부분 적용하지 않습니다.'),labelInput('백업 파일',file),labelInput('가져오기 방식',importMode),actions(importButton),node('h3',{},'시간 알림'),node('label',{for:'timer-warning-setting'},warnings,'10분·5분·1분 남음 알림 사용'),node('p',{},'설정 시간보다 긴 경고는 생략하며 남은 시간을 매초 읽지 않습니다. 남은 시간 확인 버튼은 언제나 사용할 수 있습니다.'),node('h3',{},'로컬 기록 삭제'),node('p',{},'브라우저와 앱에는 휴지통이 없습니다. 삭제 전 JSON 백업을 권장합니다.'),button('전체 세션 이력 삭제',async()=>{if(!window.confirm('모든 학습 세션과 답안을 영구 삭제합니다. 내려받은 백업이 없으면 복구할 수 없습니다. 삭제할까요?'))return;await state.store.clearSessions();await refreshSessions();announce('이 브라우저의 세션 이력을 삭제했습니다.');},{class:'danger'}),node('h3',{},'접근성 확인'),node('p',{},'키보드와 자동 검사를 보조 수단으로 사용합니다. Windows NVDA 수동 검증은 미실시이며 이 버전은 개발자 점검용 미리보기입니다. 화면 낭독기 단축키를 재정의하지 않습니다.'),node('a',{href:'./docs/NVDA-CHECKLIST.md',target:'_blank',rel:'noopener noreferrer'},'NVDA 수동 점검 목록 (새 탭)'));
}
function remainingText(ms){const seconds=Math.ceil((ms||0)/1000);return `남은 시간 ${Math.floor(seconds/60)}분 ${seconds%60}초`;}
let ticking=false;async function timerTick(){if(ticking||!state.session||state.session.status!=='active'||state.session.config.mode!=='timed'||!state.editor?.acquired)return;ticking=true;try{const s=state.session,t=nowState(s);if($('remaining'))$('remaining').textContent=remainingText(t.remaining);if(t.expired){if(!state.storageFailed)await edit((current)=>finalize(current,'expired',t.now));else announce('제한 시간이 끝났습니다. 저장 실패로 확정하지 못했습니다. 미저장 입력을 먼저 백업하고 저장을 다시 시도하세요.');return;}const thresholds=[600000,300000,60000];for(const value of thresholds){const key=`remaining-${value}`;if(s.config.minutes*60000>value&&t.remaining<=value&&!state.warningKeys.has(key)){state.warningKeys.add(key);await edit(current=>{if(!current.warnings.includes(key))current.warnings.push(key);return current;});if(state.settings.timerWarnings)announce(`제한 시간이 ${value/60000}분 이내로 남았습니다.`);}}if(!t.trusted&&s.clockTrusted){await edit(current=>{current.clockTrusted=false;return current;});announce('시스템 시계 차이가 감지되었습니다. 현재 탭은 단조 증가 시계를 사용하며 시간 신뢰를 낮게 표시합니다.');}}catch(error){showError(error);}finally{ticking=false;}}
window.addEventListener('pagehide',releaseEditor);document.addEventListener('visibilitychange',()=>{if(!document.hidden)timerTick();});window.addEventListener('beforeunload',event=>{if(state.storageFailed){event.preventDefault();event.returnValue='';}});
async function bootstrap(){installNavigation();try{state.store=await openStore();state.settings=await state.store.meta('settings')||state.settings;const cached=await state.store.meta('bank');if(cached){try{validateBank(cached.bank);state.bundle=cached;state.bank=cached.bank;}catch(error){showError(new Error('저장된 문제 은행이 손상되었습니다. 세션 스냅샷은 보존하며 새 은행을 확인합니다.'));}}await refreshSessions();for(const s of state.sessions.filter(s=>s.status==='active'&&s.config.mode==='timed')){const t=timeState(s,Date.now());if(t.expired)await state.store.update(s.sessionId,s.revision,current=>finalize(current,'expired',t.now));}await renderHome();await checkUpdate(false);if(state.view==='오늘의 연습'&&state.bank)await renderHome();$('version').textContent=`앱 ${APP_VERSION} · 문제 은행 ${state.bank?.bankVersion||'불러오지 못함'}`;setInterval(timerTick,1000);}catch(error){showError(error);screen('저장소를 사용할 수 없습니다',node('p',{},'초기 저장을 보장할 수 없어 연습을 시작하지 않았습니다. 기존 브라우저 데이터를 지우지 말고 비공개 창·저장 공간·사이트 설정을 확인하세요.'),button('다시 시도',()=>location.reload()));}}
bootstrap();
