async function run(){
 const d=await import('../src/domain.js?v=0.2.7'),b=await import('../src/backup.js?v=0.2.7'),st=await import('../src/storage.js?v=0.2.7'),{fixture}=await import('./fixture.mjs?v=0.2.7');
 const results=[];const eq=(a,b,msg)=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(`${msg}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`);};
 const check=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message,stack:e.stack});}};
 const bank=fixture(), config={type:'written',subjectId:'all',kind:'practice',mode:'timed',count:2,minutes:1,optionCount:5,pool:'all'};
 const make=(id='storage')=>d.startSession(d.prepareSession(bank,config,[],3,id),Date.now());
 const store=await st.openStore({open:(name,version)=>indexedDB.open(name+'-isolated-qa-'+Date.now(),version)});
 await check('AC06 two concurrent IndexedDB CAS writes conflict instead of silently overwriting',async()=>{let s=make('race');await store.insert(s);const q=s.items[0];const r=await Promise.allSettled([store.update(s.sessionId,0,v=>d.setAnswer(v,q.instanceId,q.options[0].optionId)),store.update(s.sessionId,0,v=>d.setAnswer(v,q.instanceId,q.options[1].optionId))]);eq(r.filter(r=>r.status==='fulfilled').length,1,'success count');eq(r.filter(r=>r.status==='rejected'&&r.reason.code==='CONFLICT').length,1,'conflict count');eq((await store.session('race')).revision,1,'stored revision');});
 await check('AC06 browser Web Locks exclude second editor until release',async()=>{const a=await st.acquireEditor('lock');const b=await st.acquireEditor('lock');eq(a.acquired,true,'first lock');eq(b.acquired,false,'second lock');a.release();await new Promise(r=>setTimeout(r,0));const c=await st.acquireEditor('lock');eq(c.acquired,true,'lock after release');c.release();});
 await check('AC07 concurrent expiry/submit results atomically stored once',async()=>{let s=make('expiry');await store.insert(s);const now=s.expiresAt+1000;const r=await Promise.allSettled([store.update(s.sessionId,0,v=>d.finalize(v,'submitted',now)),store.update(s.sessionId,0,v=>d.finalize(v,'expired',now))]);eq(r.filter(r=>r.status==='fulfilled').length,1,'terminal commit count');const end=await store.session('expiry');eq(end.status,'expired','reason');eq(end.attempts.length,2,'attempt count');eq(end.elapsedMs,60000,'capped time');});
 await check('AC13 export/import exact roundtrip and duplicate/mismatching ID behavior',async()=>{const original=await store.sessions();const parsed=b.parseBackup(b.exportBackup(original));eq(parsed.sessions,original,'roundtrip');const imported=await store.importSessions(parsed.sessions);eq(imported,{imported:0,duplicates:2,conflicts:0},'duplicates');const changed=d.copy(original);changed[0].currentIndex=1;const clash=await store.importSessions(changed);eq(clash.conflicts,1,'conflict count');eq(await store.sessions(),original,'existing preserved');});
 await check('AC13 damaged/tampered/unknown version backup refused',async()=>{const original=await store.sessions();const exportObj=JSON.parse(b.exportBackup(original));let count=0;for(const raw of ['{',JSON.stringify({...exportObj,schemaVersion:99}),JSON.stringify({...exportObj,sessions:[original[0],original[0]]}),JSON.stringify({...exportObj,sessions:[{...original[0],answers:{fake:'x'}}]}),'x'.repeat(b.MAX_BACKUP_BYTES+1)]){try{b.parseBackup(raw);}catch{count++;}}eq(count,5,'invalid backup rejections');eq(await store.sessions(),original,'preserved');});
 await check('AC11 conversion writes old and next atomically; rollback on duplicate new ID',async()=>{const old=make('convert');await store.insert(old);await store.convert(old.sessionId,0,v=>d.convertToUntimed(v,'untimed'));eq((await store.session('convert')).status,'converted','old status');eq((await store.session('untimed')).config.mode,'untimed','new mode');const other=make('convert-bad');await store.insert(other);let failed=false;try{await store.convert(other.sessionId,0,v=>d.convertToUntimed(v,'untimed'));}catch{failed=true;}eq(failed,true,'duplicate destination rejected');eq((await store.session('convert-bad')).status,'active','old rolled back');});
 await check('AC12 valid update saved and bad hash/schema/network preserve last good bundle',async()=>{const data=JSON.stringify(bank);const manifest={schemaVersion:1,bankVersion:bank.bankVersion,releasedAt:bank.releasedAt,file:'releases/qa.1/bank.json',sha256:await d.sha256(data)};const fetcher=async url=>new Response(url.pathname.endsWith('manifest.json')?JSON.stringify(manifest):data,{status:200});await st.updateBank(store,location.href,fetcher);const before=await store.meta('bank');for(const bad of ['hash','schema','network','json','mismatch']){let rejected=false;try{await st.updateBank(store,location.href,async url=>{if(bad==='network')throw Error('Offline');let m={...manifest};if(bad==='hash')m.sha256='f'.repeat(64);if(bad==='schema')m.schemaVersion=999;if(bad==='mismatch')m.bankVersion='other';return new Response(url.pathname.endsWith('manifest.json')?(bad==='json'?'{':JSON.stringify(m)):data,{status:200});});}catch{rejected=true;}eq(rejected,true,`${bad} rejected`);eq(await store.meta('bank'),before,`${bad} retained last good`);}});
 await check('AC17 transaction abort preserves old session and reports failure',async()=>{const before=await store.session('race');let failed=false;try{await store.update('race',before.revision,()=>{throw new DOMException('Simulated quota','QuotaExceededError')});}catch{failed=true;}eq(failed,true,'failure surfaced');eq(await store.session('race'),before,'original preserved');});
 await check('AC17 IndexedDB unavailable surfaces error',async()=>{let failed=false;try{await st.openStore(null);}catch(e){failed=e.message.includes('IndexedDB');}eq(failed,true,'explicit unavailable');});
 return results;
}
document.getElementById('run').addEventListener('click',async()=>{ const output=document.getElementById('output');output.textContent='Running isolated QA';try{const results=await run();output.textContent=JSON.stringify({timestamp:new Date().toISOString(),userAgent:navigator.userAgent,results},null,2);}catch(error){output.textContent=JSON.stringify({status:'HARNESS_ERROR',message:error.message,stack:error.stack},null,2);}});
