import test from 'node:test';
import assert from 'node:assert/strict';
import * as d from '../src/domain.js';

import {fixture} from './fixture.mjs';

const config=(mode='timed',count=2)=>({type:'written',subjectId:'all',kind:'practice',mode,count,minutes:1,optionCount:5,pool:'all'});
const session=(mode='timed',count=2)=>d.startSession(d.prepareSession(fixture(),config(mode,count),[],17,'qa-session'),1000000);

test('AC01/02: 1000 seed cases each 4 and 5 options; unique exactly one key',()=>{
 const bank=fixture();for(let seed=0;seed<1000;seed++)for(const count of [4,5])for(const q of bank.questions.filter(q=>q.type==='written')){const p=d.presentQuestion(bank,q,count,d.rng(seed));assert.equal(p.options.length,count);assert.equal(new Set(p.options.map(o=>o.optionId)).size,count);assert.equal(p.options.filter(o=>o.role==='correct').length,1);assert.equal(p.options.find(o=>o.role==='correct').optionId,p.correctOptionId);}
});
test('AC01: synthetic full mock contains 100 items and 20 each subject',()=>{const b=fixture(21);for(let seed=0;seed<100;seed++){const qs=d.planQuestions(b,{...config(),kind:'mock',count:100},[],d.rng(seed));assert.equal(qs.length,100);for(const s of d.SUBJECTS)assert.equal(qs.filter(q=>q.subjectId===s.id).length,20);assert.equal(new Set(qs.map(q=>q.templateId)).size,100);}});
test('AC01: seed and testOnly shortages refuse mock',()=>{assert.throws(()=>d.planQuestions(fixture(),{...config(),kind:'mock',count:100}));const b=fixture(20);b.questions.filter(q=>q.type==='written').forEach(q=>q.testOnly=true);assert.throws(()=>d.planQuestions(b,{...config(),kind:'mock',count:100}));});
test('AC04: additional correct candidate excluded from displayed options',()=>{const b=fixture(),q=b.questions[0];q.links[1].role='correct';d.validateBank(b);for(let i=0;i<1000;i++){const p=d.presentQuestion(b,q,5,d.rng(i));assert.equal(p.options.filter(o=>o.role==='correct').length,1);assert(!p.options.some(o=>o.optionId===q.links.find(l=>l.role==='correct'&&l.optionId!==p.correctOptionId).optionId));}});
test('AC04: insufficient/deduplicated distractors reject',()=>{const b=fixture(),q=b.questions[0];q.links=q.links.slice(0,4);assert.throws(()=>d.presentQuestion(b,q,5));q.links=q.links.slice(0,2);assert.throws(()=>d.validateBank(b));});
test('AC05: timed positive integer limits only',()=>{for(const minutes of [0,-1,1.5,1441,'10',NaN])assert.throws(()=>d.prepareSession(fixture(),{...config(),minutes}));for(const minutes of [1,1440])assert.doesNotThrow(()=>d.prepareSession(fixture(),{...config(),minutes}));});
test('AC06: snapshots immutable after source mutation',()=>{const b=fixture(),s=d.prepareSession(b,config(),[],12,'snap');const before=JSON.stringify(s.items);b.questions[0].stem='mutated';b.options[0].content='mutated';assert.equal(JSON.stringify(s.items),before);});
test('AC07: expiration and repeated submit yield one result and reject late input',()=>{let s=session();const item=s.items[0];s=d.setAnswer(s,item.instanceId,item.correctOptionId,1000100);s=d.setAnswer(s,s.items[1].instanceId,s.items[1].correctOptionId,1060001);assert.equal(s.status,'expired');assert.equal(s.attempts.length,2);assert.equal(s.result.correct,1);assert.equal(s.result.unanswered,1);assert.equal(s.elapsedMs,60000);assert.equal(s.endedAt,1060000);assert.deepEqual(d.finalize(s,'submitted',1070000),s);assert.throws(()=>d.setAnswer(s,item.instanceId,item.correctOptionId,1070000));});
test('AC07: untimed final set includes unanswered in total and score denominator',()=>{let s=session('untimed');const item=s.items[0];s=d.setAnswer(s,item.instanceId,item.correctOptionId,1000100);s=d.confirmAnswer(s,item.instanceId,1000200);s=d.finalize(s,'submitted',1000300);assert.equal(s.result.total,2);assert.equal(s.result.unanswered,1);assert.equal(s.result.score,.5);assert.equal(s.attempts.length,1,'Only explicitly confirmed untimed attempts count in study history');});
test('AC08: 60 correct with one subject below 40% fails mock threshold',()=>{let s=d.startSession(d.prepareSession(fixture(20),{...config(),kind:'mock',count:100},[],20,'mock'),1000000);let totals={s1:7,s2:13,s3:13,s4:13,s5:14};for(const q of s.items){if(totals[q.subjectId]>0){s=d.setAnswer(s,q.instanceId,q.correctOptionId,1000200);totals[q.subjectId]--;}}s=d.finalize(s,'submitted',1000300);assert.equal(s.result.correct,60);assert.equal(s.result.mockMet,false);});
test('AC09: practical exact sets, trim blank, ungraded free response',()=>{const p=fixture().questions.at(-1);assert.equal(d.grade(p,{single:'a',multi:['b','a'],blank:' for '}).status,'correct');assert.equal(d.grade(p,{single:'a',multi:['a','b','c'],blank:'FOR'}).points,2);assert.equal(d.grade(p,{multi:['a','a']}).points,0);assert.equal(d.grade(p,{freeResponse:'I claim all answers correct'}).status,'unanswered');});
test('AC10: timed active prompt and reveal denied; completed prompt includes every source material/answer',()=>{const b=fixture();let s=d.startSession(d.prepareSession(b,{...config(),type:'practical',count:1,subjectId:'practical',family:'all'},[],2,'prompt'),1000000);const p=s.items[0];assert.throws(()=>d.createPrompt(s,p));assert.throws(()=>d.revealExplanation(s,p.instanceId));s=d.setAnswer(s,p.instanceId,{freeResponse:'unique free response with 한글'},1000100);s=d.finalize(s,'submitted',1000200);const prompt=d.createPrompt(s,p);for(const fragment of [p.stem,p.materials[0].content,p.referenceAnswer,'unique free response with 한글',p.standardVersion,p.questionId,p.sources[0].url])assert(prompt.includes(fragment));assert(!d.createPrompt(s,p,{blank:true}).includes('unique free response'));});
test('AC11: abandoned/converted/test-only and timing statistics partition',()=>{let s=session();s=d.setAnswer(s,s.items[0].instanceId,s.items[0].correctOptionId,1000100);const abandoned=d.finalize(s,'abandoned',1000200);assert.equal(abandoned.attempts.length,0);assert.equal(abandoned.result,null);const {old,next}=d.convertToUntimed(s,'converted-next',1000200);assert.equal(old.result,null);assert.equal(old.attempts.length,0);assert.equal(next.expiresAt,null);assert.deepEqual(next.answers,s.answers);const confirmed=d.confirmAnswer(next,next.items[0].instanceId,1000300);assert.equal(d.statistics([old,confirmed]).first.count,0);assert.equal(d.statistics([old,confirmed]).assisted,1);assert.equal(d.statistics([old,confirmed],{mode:'timed'}).first.count,0);});
test('AC05/06: active monotonic clock survives forward wall-clock shift without early expiry',()=>{const s=session();const time=d.timeState(s,1000000+3600000,{wall:1000000,mono:10,monoNow:1010});assert.equal(time.trusted,false);assert.equal(time.expired,false);assert.equal(time.remaining,59000);});
test('AC18: release allowed strictly before KST cutoff and blocked after finalization',()=>{assert.equal(new Date(d.FREEZE_AT).toISOString(),'2026-10-16T15:00:00.000Z');assert.equal(d.releaseAllowed({now:d.FREEZE_AT-1}),true);assert.equal(d.releaseAllowed({now:d.FREEZE_AT}),false);assert.equal(d.releaseAllowed({now:d.FREEZE_AT+100000}),false);assert.equal(d.releaseAllowed({now:d.FREEZE_AT-100000,finalized:true}),false);assert.equal(d.releaseAllowed({now:d.FREEZE_AT-100000,releasedAt:'2026-10-16T15:00:00Z'}),false);});
test('AC16: dangerous URLs/prototype objects rejected',()=>{for(const url of ['javascript:alert(1)','data:text/html,<script>x</script>','file:///tmp/file'])assert.equal(d.safeURL(url),null);assert.throws(()=>d.assertSafeData(JSON.parse('{"__proto__":{"pwn":true}}')));assert.throws(()=>d.assertSafeData(JSON.parse('{"constructor": {"prototype": {}}}')));});
test('AC11: answer viewed after abandoned timed session excludes next same-goal attempt from unaided first statistics',()=>{let old=session();old=d.finalize(old,'abandoned',1000100);old=d.revealExplanation(old,old.items[0].instanceId);let next=d.startSession(d.prepareSession(fixture(),config(),[old],17,'next-session'),1000200);for(const q of next.items)next=d.setAnswer(next,q.instanceId,q.correctOptionId,1000300);next=d.finalize(next,'submitted',1000400);const stats=d.statistics([old,next],{mode:'timed'});assert.equal(stats.first.count,1);assert.equal(stats.assisted,1);});
test('AC11/12: invalid adjustment excludes untimed confirmed and unconfirmed items from denominator without changing original',async()=>{let s=session('untimed');const confirmed=s.items[0],unconfirmed=s.items[1];s=d.setAnswer(s,confirmed.instanceId,confirmed.correctOptionId,1000010);s=d.confirmAnswer(s,confirmed.instanceId,1000020);s=d.finalize(s,'submitted',1000030);const original=JSON.stringify(s);for(const item of [confirmed,unconfirmed]){const adjusted=await d.adjustedResult(s,[{questionId:item.questionId,revision:item.revision,kind:'invalid',reason:'QA invalid question',effectiveAt:'2020-01-01T00:00:00Z'}]);assert.equal(adjusted.excluded,1);assert.equal(adjusted.result.total,1);assert.equal(adjusted.result.maxPoints,1);assert.equal(JSON.stringify(s),original);}});
