import * as d from '../src/domain.js';
export function fixture(perSubject=2) {
 const bank={schemaVersion:1,bankVersion:'qa.1',releasedAt:'2026-10-01T00:00:00Z',syllabusVersion:'QA synthetic',changeSummary:'Synthetic QA only; do not publish',subjects:d.SUBJECTS,sources:[{id:'qa',title:'QA fixture, not learning material',url:'https://example.com/qa',version:'1',checkedAt:'2026-10-01',location:'fixture',evidence:'synthetic',rights:'Synthetic test fixture'}],options:[],questions:[]};
 for(const sub of d.SUBJECTS)for(let i=0;i<perSubject;i++) {
  const qid=`${sub.id}.${i}`;
  const q={questionId:qid,revision:1,templateId:qid,learningGoalRevision:1,type:'written',subjectId:sub.id,topicIds:['qa'],stem:`Synthetic ${qid}: select the word correct`,explanation:'QA explanation',standardVersion:'QA',difficulty:'QA',verificationStatus:'published',testOnly:false,reviewNote:'Synthetic structure only',sourceRefs:['qa'],optionMode:'exclusive',supportedOptionCounts:[4,5],links:[]};
  for(let j=0;j<6;j++){const oid=`${qid}.o${j}`;bank.options.push({optionId:oid,revision:1,content:j===0?`correct ${qid}`:`wrong ${qid} ${j}`,explanation:`basic ${oid}`});q.links.push({optionId:oid,optionRevision:1,role:j===0?'correct':'distractor',contextExplanation:`context ${oid}`,compatibilitySetId:'qa'});}
  bank.questions.push(q);
 }
 const p={questionId:'p.1',revision:1,templateId:'p.1',learningGoalRevision:1,type:'practical',subjectId:'practical',family:'implementation',topicIds:['qa'],stem:'Synthetic practical',explanation:'QA practical explanation',standardVersion:'QA',difficulty:'QA',verificationStatus:'published',testOnly:false,reviewNote:'Synthetic only',sourceRefs:['qa'],materials:[{filename:'code.html',content:'<img src=x onerror="globalThis.__INJECTED=true">\n<script>globalThis.__INJECTED=true</script>'}],parts:[{partId:'single',kind:'single',prompt:'Choose A',points:2,explanation:'A',choices:[{id:'a',text:'A'},{id:'b',text:'B'}],correct:['a']},{partId:'multi',kind:'multi',prompt:'Choose A and B exactly',points:3,explanation:'A+B',choices:[{id:'a',text:'A'},{id:'b',text:'B'},{id:'c',text:'C'}],correct:['a','b']},{partId:'blank',kind:'text',prompt:'Enter for with surrounding whitespace ignored',points:5,explanation:'for',accepted:['for'],normalization:'trim'}],referenceAnswer:'QA reference answer',freeResponsePrompt:'Explain freely',rubric:[{criterion:'QA',points:10,description:'Synthetic only'}]};
 bank.questions.push(p);return d.validateBank(bank);
}
